### PR TITLE
Bump express and dependencies

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves some dependabot alerts. This still leaves open a couple of cases for path-to-regexp:

* sinon depends on it indirectly, but this is only used in tests, so it doesn't affect production.
* s3rver depends on it indirectly, but this is only used locally, not in production.

### CODE REVIEW

**Review by nwalters512 — APPROVED** [review]

**Comment by jonatanschroeder** [comment]
Not sure what is causing the test issues, but I don't have the bandwidth to check further now. Besides, it seems express 4.20.0 also has some security issues (https://github.com/expressjs/express/issues/5947), so holding back for now.

**Comment by jonatanschroeder** [comment]
> it seems express 4.20.0 also has some security issues ([expressjs/express#5947](https://github.com/expressjs/express/issues/5947)), so holding back for now.

These seem to have been fixed in 4.21.0, so reopening with that version. Also merging with master to fix the issue with CI not passing.

**Comment by jonatanschroeder** [comment]
For the accessibility tests: it seems one of the problems is that it's trying to get to pages like `/pl/instances.json`. The route does not exist, but `/instances.json` is found here:
https://github.com/PrairieLearn/PrairieLearn/blob/0f21b9921f290cdacb5d522168f1a5396a5fad22/apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.ts#L34

So for some reason it is attempting to go to routes that don't take the whole context into account. Not sure if this is a problem with express-list-endpoints or another testing library's integration with the new express. The same issue happens with several other routes that are taken out of context (`/pl/:job_id`, `/pl/navbar`, etc.).

**Comment by nwalters512** [comment]
I'm looking into this. I'm betting this is a problem with `express-list-endpoints`.

**Comment by nwalters512** [comment]
I submitted a PR with the necessary changes for new versions of Express: https://github.com/AlbertoFdzM/express-list-endpoints/pull/96

**Comment by nwalters512** [comment]
I manually copied over the changes from that PR into PrairieLearn's `node_modules` and confirmed that the accessibility tests now pass. I'll give the maintainer a week or so to integrate these changes, but after that, I'm inclined to just fork the package.

**Comment by jonatanschroeder** [comment]
> I manually copied over the changes from that PR into PrairieLearn's `node_modules` and confirmed that the accessibility tests now pass. I'll give the maintainer a week or so to integrate these changes, but after that, I'm inclined to just fork the package.

Are you still considering forking it, or even copying its code to a simple helper file? Or maybe [an alternative](https://www.npmjs.com/package/route-list)?

**Comment by nwalters512** [comment]
I'm going to check out `route-list`, nice find! If that doesn't work, I think a local fork will be the best option.

**Comment by nwalters512** [comment]
Lol, I take it back, `express-list-endpoints` is in fact a dependency of `route-list`:

https://github.com/VladimirMikulic/route-list/blob/f0edff975931d68577e9875f08888c86a499141d/package.json#L42

**Comment by nwalters512** [comment]
This was ultimately done as part of #10787.

**Comment by jonatanschroeder** [comment]
> This was ultimately done as part of #10787.

Express was not updated in that PR...

**Comment by nwalters512** [comment]
> Express was not updated in that PR...

It most certainly was:

https://github.com/PrairieLearn/PrairieLearn/blob/b62c1b3fb7679242b7b3aa0dc7011897569bccec/yarn.lock#L8910-L8911

**Comment by jonatanschroeder** [comment]
> > Express was not updated in that PR...
> 
> It most certainly was:
> 
> https://github.com/PrairieLearn/PrairieLearn/blob/b62c1b3fb7679242b7b3aa0dc7011897569bccec/yarn.lock#L8910-L8911

Ah, in the yarn.lock file, but not in the dependencies and package.json files. Is that a problem?

**Comment by nwalters512** [comment]
The lockfile is always the source of truth for what's installed, and `4.21.1` most certainly satisfies the semver range `^4.19.2`. If it bothers you that the semver range doesn't have a lower bound of the most recent version, you're welcome to patch up this PR and get it ready to merge. If not, please close it again.

**Comment by jonatanschroeder** [comment]
For some reason I thought that this PR was also updating some workspaces and grader images, which would require a separate yarn.lock, but that's not the case. Closing.

**Pull request closed without merging**
