### PR TITLE
Only show actions dropdown if permissions allow actions

### LINKED ISSUE #9648: Instructor assessment questions action button has no actions
I don't know if this is an error case, or if we want to present a different UX. While tabbing through https://us.prairielearn.com/pl/course_instance/152149/instructor/assessment/2410572/questions I noticed:

image

If there are no actions, should we say that? Or change the button?

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #9648.

### CODE REVIEW

**Review by mylesw27 — APPROVED** [review]

**Review by mylesw27 — APPROVED** [review]
Tested locally and works great. Do we want to do this in the assessment instances page as well?

**Comment by nwalters512** [comment]
@mylesw27 I realized that I should do that right after opening this PR, check the second commit!

**Comment by mylesw27** [comment]
> @mylesw27 I realized that I should do that right after opening this PR, check the second commit!

Sorry, for clarification here, I meant `instructorAssessmentInstances` like the page that displays the summaries of all instances. I saw your second commit and made me wonder if we should add it there as well. 
Screenshot 2024-03-29 at 9 54 28 AM

**Comment by nwalters512** [comment]
Ah! I didn't realize we did this on the instances page. Maybe this is a better way to go? If nothing else, it'd be good to be consistent.

**Comment by jonatanschroeder** [comment]
I like the instances page behavior better. A user that has different permissions in different courses will have more clarity about why the actions are not available.

**Comment by nwalters512** [comment]
I made that change in e1887c4.

**Review by mylesw27 — APPROVED** [review]

**Review by jonatanschroeder — APPROVED** [review]

**Pull request merged**
