### PR TITLE
Show past submissions

### PR DESCRIPTION
**Pull request by rbessick5**
Partially addresses #255 but does not fully implement feedback (due to the limitations discussed in #270 ).

### CODE REVIEW

**Comment by kevinwang** [comment]
Can you use four space tabs to conform to (what appears to be) the project coding convention?

**Comment by rbessick5** [comment]
Done (foolish me for not checking my editor settings)!

**Comment by rbessick5** [comment]
Matt, based on our discussion this morning, I've changed the submission rendering to draw a panel for each submission and put one copy of submission.html into each panel. The panel headings show the submission index, datestamp, and correct/incorrect/graded status.

I would like to indicate grading status using the same labels that PL uses elsewhere, but the panel-heading class doesn't seem to like having, e.g., '<span class="label label-success>correct</span>' within them (they don't render), so I've just put the word there for now. I've also rigged the panel style to reflect the grading status (i.e., panel-info for a submission, panel-danger for a (graded) incorrect, panel-success for a (graded) correct), but this may prove to be too obnoxious and/or confusing (if the submit panel is also changing color to reflect an unsaved response in progress).

The first submission panel also clips the bottom of the submit button (when available), and I'm not sure what the best way to buffer this is. It gives the proper space to the answer panel.

**Comment by mwest1066** [comment]
Ray, this sounds excellent.

I think labels should work within panel headings. I just tried them out and it looks fine. Either within the `<h3>` or outside it, both worked. For example, this works for me:

        <div class="panel-heading">
          <h3 class="panel-title">
            This is the title
            <span class="label label-default">Default</span>
          </h3>
        </div>

**Comment by rbessick5** [comment]
The render issue was my fault -- I used a double-moustache instead of a triple-moustache, so Moustache was escaping the label span. The most recent commit has the labels working correctly.

**Comment by mwest1066** [comment]
Closing without merge as this ended up being very messy to implement in v1. Issue #255 remains open and still needs to be implemented in v2.

**Pull request closed without merging**
