### PR TITLE
Fix duplicate answers in template/multiple-choice question

### PR DESCRIPTION
**Pull request by nwalters512**
If we were (un)lucky enough to select $a = 1.8$ and $b = 9$, we'd end up in a situation where the first two distractors were $7.2$. The easiest way to fix this was to adjust the range. I used the following code to verify that there weren't any more duplicate distractors:

```py
import numpy as np

for a in np.arange(2, 5.1, 0.1):
    for b in np.arange(6, 12):
        correct = round(a * b, 4)
        distractor_1 = round((a - 1) * b, 4)
        distractor_2 = round(b - a, 4)
        distractor_3 = round((a + 1) * b, 4)

        count_set = set()
        count_set.add(correct)
        count_set.add(distractor_1)
        count_set.add(distractor_2)
        count_set.add(distractor_3)

        if len(count_set) != 4:
            print("Duplicate found")
            print(f"a: {a}, b: {b}")
            print(f"correct: {correct}")
            print(f"distractor_1: {distractor_1}")
            print(f"distractor_2: {distractor_2}")
            print(f"distractor_3: {distractor_3}")
```

### CODE REVIEW

**Comment by mwest1066** [comment]
Don't we already have code in `pl-multiple-choice` to handle this? Or am I just remembering that we talked about fixing this problem but never actually did it?

**Comment by nwalters512** [comment]
We do have code to catch this; the reason I know that is because this question manifests as a flaky test:

https://github.com/PrairieLearn/PrairieLearn/blob/38233ae187fb734b10b4b78a44ab83f0a6d1cdf6/apps/prairielearn/src/tests/exampleCourseQuestions.test.ts#L77-L86

But more broadly, this is a template question; we don't ever want to knowingly have a template question that is known to fail in certain cases.

**Review by eliotwrobson — APPROVED** [review]
I'm wondering whether it's better to include rejection sampling in the server code because this is an example, but logic looks fine.

**Review by jonatanschroeder — APPROVED** [review]

**Comment by nwalters512** [comment]
> I'm wondering whether it's better to include rejection sampling in the server code because this is an example, but logic looks fine.

This could be useful; right now I'm just focusing on making the test suite less flaky. We could discuss at the dev meeting this week if there's any more generic fix we could use here and maybe document?

That said, I'm generally not super worried about this for anything that isn't run as part of an automated test suite or made available as template material, as the "try again" button will be really obvious for users.

**Pull request merged**
