### PR TITLE
added an option to auto-refresh table when looking at the students tab

### PR DESCRIPTION
**Pull request by nitahieb**
@jonatanschroeder 
Added a feature to auto refresh the students tab when looking at an assessment

### CODE REVIEW

**Comment by nitahieb** [comment]
For just the autorefresh feature I was wondering if there's any standardization on what the website should look like?
RIght now I put the autorefresh under the action for all instances.
image

**Comment by jonatanschroeder** [comment]
> For just the autorefresh feature I was wondering if there's any standardization on what the website should look like?
> RIght now I put the autorefresh under the action for all instances.

I think it may be best to show it at the bottom. Also, in terms of style, take a look at boostrap: https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios-1

**Comment by nitahieb** [comment]
Do you mean at the bottom of the page outside of the table? Or at the bottom of the table?

**Comment by jonatanschroeder** [comment]
> Do you mean at the bottom of the page outside of the table? Or at the bottom of the table?

Not sure, can you try both and see what looks better?

**Comment by jonatanschroeder** [comment]
I'm going to close this, since (based on #4543 and a possible expectation of migrating this page to `bootstrap-table` as well) it may be better to work with a different paradigm to refresh data using JSON instead of full page refresh.

**Pull request closed without merging**
