### PR TITLE
Add gvsu.edu as an institution

### PR DESCRIPTION
**Pull request by mwest1066**

### CODE REVIEW

**Comment by trombonekenny** [comment]
Is this to show me how to do it, or to beg for help making it better?

**Comment by mwest1066** [comment]
Hahaha, I guess it’s doing both of those things as well, but the immediate reason is that Erin Carrier needs it 😄

**Comment by mwest1066** [comment]
It did remind me of just how horrible this is 😄

**Comment by trombonekenny** [comment]
Hey at least ENUMs aren't a part of it. I'll start working on an institutions-in-the-db branch but in the meantime, putting this in for gvsu and umd might be a smart start.

**Pull request merged**
