### PR TITLE
Manual question config

### PR DESCRIPTION
**Pull request by andrewstec**
@mebird Copy and paste of our plan from Slack:

- [ ] Backend: Create a manual grading flag in the config. Give a percentage towards the manual graded score. Dictate any DB changes/workflow changes.
- [ ] UI: Load any question with this view. Do not allow students to access this page. Only render for pages with a grading config. Get graded score data (manual & automatic) and hit an endpoint statically.
JSON structure in config file.
- [ ] How to resolve changes to the config file (do we have a reset/make happy button)?
- [ ] Future: building instructor menus, updating grading toggles. This menu will likely have a button to indicate if the config file changes.

### CODE REVIEW

**Comment by andrewstec** [comment]
This is still a work in progress, but I wanted to create a separate PR thread to discuss this logic.

**Comment by andrewstec** [comment]
@mebird We are now at a place where data is being imported into the database: 

```
-[ RECORD 1 ]-----------------------+--------------------------------------------------------
id                                  | 95
uuid                                | b0444a41-1472-4aa5-a024-ee1091bdab8e
qid                                 | demo/autograder/codeUpload
directory                           | demo/autograder/codeUpload
template_directory                  | 
type                                | Freeform
title                               | Demo: Fibonacci function, file upload, external grading
options                             | 
client_files                        | {client.js,question.html,answer.html}
number                              | 487
grading_method                      | External
course_id                           | 1
topic_id                            | 2
deleted_at                          | 
external_grading_enabled            | t
external_grading_image              | prairielearn/grader-python
single_variant                      | t
external_grading_files              | 
external_grading_entrypoint         | /python_autograder/run.sh
external_grading_timeout            | 20
partial_credit                      | t
external_grading_enable_networking  | 
dependencies                        | {}
workspace_image                     | 
workspace_graded_files              | 
workspace_port                      | 
workspace_args                      | 
workspace_url_rewrite               | 
workspace_home                      | 
workspace_sync_ignore               | 
sync_job_sequence_id                | 
sync_errors                         | 
sync_warnings                       | 
manual_grading_enabled              | t
manual_grading_autograde_score_perc | 
manual_grading_manual_score_perc    | 
manual_grading_override_score       | f
```

This occurs when we sync questions. If you want to work off of this branch, feel free to. I can also merge in updates from your branch too. Whatever works!

If you want to use this branch, there is a migration. If you run into database issues for some reason, you may want to connect to postgres with `psql`. 

1) psql
2) DROP DATABASE prairielearn_database_name_you_are_using_locally
3) CREATE DATABASE prairielearn_database_name_you_are_using_locally

Obviously you will lose all of your local data though.

I will continue on Monday regardless.

**Comment by mebird** [comment]
> @mebird We are now at a place where data is being imported into the database from the Config:
> 
> ```
> -[ RECORD 1 ]-----------------------+--------------------------------------------------------
> ....
> ```
> 
> This occurs when we sync questions. If you want to work off of this branch, feel free to. I can also merge in updates from your branch too. Whatever works!
I can work off a new branch forked from this to clean up the UI & the logic to display the grading UI from the config file, since I'll be tearing out a few chunks of code that I had from before.

For now, I'll mock up the interface with static values for the "autograded total score", the "manual graded score", and the "grading status" of the question. For sake of consistency of the UI, we should display the two "parts" of the final score separately. Just to confirm, we will add these fields to the instance question, correct? **It's nasty, but we will have to re-calculate the total score from its parts upon question sync, or require an instructor to otherwise recalculate the final score**.

I know @cheeren also mentioned having a config option for "if the score is 100%, set the manual score to full marks and mark the instance as graded".
> 
> If you want to use this branch, there is a migration. If you run into database issues for some reason, you may want to connect to postgres with `psql`.
> 
> 1. psql
> 2. DROP DATABASE prairielearn_database_name_you_are_using_locally
> 3. CREATE DATABASE prairielearn_database_name_you_are_using_locally
> 
> Obviously you will lose all of your local data though.
I've been running everything dockerized, so I'll just kill my current database.

Since this page will query this config every time it loads, syncing shouldn't be a concern.
> I will continue on Monday regardless.
Sounds good. I'm going to close my old PR, and I'll create a new branch off of this one to work off of.

**Comment by andrewstec** [comment]
@mebird 

I will remove the views from this PR then, but leave the endpoint with their controller logic. I will need those areas of code to demonstrate functionality and for you to easily interface with something. Can we keep the endpoints that you had defined? 

Sure, that merge logic sounds great. Small feature merges are what Matt prefers.

We may need to discuss the manual grading score re-calculation. At first glance, it seems that the manual re-grading should be part of the re-grading feature that is being built out by the other team. We may have to ask for their insight and ensure it works with Cinda's vision.

At this point in time, I think the instructor should either manually re-grade the score or it should be re-graded when "re-grade" is pressed using the last data available. If the question format has changed, then we either eliminate old manual grades based on the latest config or require more manual grading on the UI before it can be manually graded.

**Feature additions:** 

- I will be sure to add the two score parts, manual and autograded, to the database. Thanks for the heads-up! 
- We can definitely add in the 100% autograde score leads to a 100% manual score option.

**Comment by mebird** [comment]
> @mebird
> 
> I will remove the views from this PR then, but leave the endpoint with their controller logic. I will need those areas of code to demonstrate functionality and for you to easily interface with something. Can we keep the endpoints that you had defined?

Yes! I'm cleaning up some fires tonight for a class project, but I'm hoping to make a quick PR to just leave in the endpoint code, and chop off any extra "ui" code. I'll create a new branch from this, and then push up the cleaned up code on this branch.

> Sure, that merge logic sounds great. Small feature merges are what Matt prefers.
> 
> We may need to discuss the manual grading score re-calculation. At first glance, it seems that the manual re-grading should be part of the re-grading feature that is being built out by the other team. We may have to ask for their insight and ensure it works with Cinda's vision.
>
> At this point in time, I think the instructor should either manually re-grade the score or it should be re-graded when "re-grade" is pressed using the last data available. If the question format has changed, then we either eliminate old manual grades based on the latest config or require more manual grading on the UI before it can be manually graded. <-- Not set on this logic, but it is what comes to mind at first glance. Needs input.

Sounds good to me. I'm just always paranoid of instructors changing things on a whim in PL, since a lot of feature requests down the line stem from this idea of changing things on the fly, and expecting PL to act a certain way.

If this doesn't make it into our MVP, we just need to make sure to include notes about it in the release notes and bold 'em.

> **Feature additions:**
> 
> * I will be sure to add the two score parts, manual and autograded, to the database. Thanks for the heads-up!

Awesome! I can move onto a majority of the frontend then as soon as we have the names for those "parts of the score" finalized. For now, I'll just use string constants to access fields so it'll be easy to make those changes later on.

**Comment by andrewstec** [comment]
Important note from Cinda regarding grading weight logic: 

```
OK!! general recap. IMO this is all just a re-ordering of what we want to do. We need to pivot away from thinking about partials, for the moment.  Assume, for the moment, that there are few elements on a page. In the question’s info.json, we specify a manualgrading flag, and a manual grading mode. The mode options are
1) override prior grade, which allows for 100% of the question to be determined by the value entered manually. The prior grading info must be seen here (we have to know what we’re overwriting.
2) weighted grading, which sets aside x% of the final mark for manual score, and (100-x)% for AG score. (is 1) just 2) but with x == 100?)
3) filter by score: only MG submissions whose original scores are below a threshold.
The order in which the grading is done is: AG(+postgrade), EG(+postgrade), MG(+postgrade).
```

**Comment by andrewstec** [comment]
I discovered some interesting things today. There is a lot of logic that I am trying to understand regarding grading that takes place for Exam and Homework types.

We knew about partial scores for some time, but they're not relevant here. 

Each time a grading job is about to be inserted (for an internal, external, or manual grading operation): 

- `instance_questions_update_in_grading(instance_question_id, authn_user_id)` SQL sproc runs.
- `assessment_instances_grade(assessment_instance_id, authn_user_id, credit)` SQL sproc runs.

Each of the functions above treats `score_perc_in_grading` differently. The instance_question update will hardcode the `score_perc_in_grading` value on an `instance_question` as 0. On the other hand, the `assessment_instances_grade` function will update the `score_perc_in_grading` value with `score_perc_in_grading := max_possible_score_perc - score_perc;`

Assessment_instances_grade:

- We define `points` on an assessment instance by taking the least of the `total_points` and `max_points` number values. 
- There are calculations for computing the percentage, etc.
- We label an instance_question object as used_for_grade = true when this operation runs.
- Then we update these values in the assessment_instance: 

```
    UPDATE assessment_instances AS ai
    SET
        points = new_values.points,
        points_in_grading = new_values.points_in_grading,
        score_perc = new_values.score_perc,
        score_perc_in_grading = new_values.score_perc_in_grading,
        modified_at = now()
    WHERE ai.id = assessment_instance_id
    RETURNING ai.*
    INTO new_assessment_instance;
```

Not entirely sure why we differentiate between scores that are `in_grading` and not.

**Pull request closed without merging**
