### PR TITLE
[Outdated - See Linked PR] Question Reset Feature

### PR DESCRIPTION
**Pull request by EricJ19**
Feature to allow questions to be marked as broken to force students to load a new, corrected variant. Based on original [PR](https://github.com/PrairieLearn/PrairieLearn/pull/3552) from the main PL development and a [PR from CS374 PL development ](https://github.com/jeffgerickson/pl-uiuc-cs374/issues/396). This PR contains a simple bug fix that previously prevented users from regenerating a correct variant among other bug fixes and changes.

### CODE REVIEW

**Review by EricJ19 — COMMENTED** [review]
I have reviewed and hereby sign the CLA

**Review by EricJ19 — COMMENTED** [review]
recheck

**Comment by EricJ19** [comment]
> I have reviewed and hereby sign the CLA

**Comment by eliotwrobson** [comment]
recheck

**Comment by EricJ19** [comment]
Hi @nwalters512 could you please approve running workflows since I am a first-time contributor? I am part of the CS374 PraireLearn development team working on this main repository feature, thank you.

**Comment by EricJ19** [comment]
Hi @nwalters512 could you please approve running workflows again as I have made changes since my last request. Thank you for the help.

**Comment by EricJ19** [comment]
Hey @nwalters512 could you please approve another run? I fixed some things related to previous build errors. Thank you,

**Comment by EricJ19** [comment]
Hi @nwalters512 sorry to another mention but could you please approve another run? Thank you.

**Pull request closed without merging**
