### PR TITLE
Replace npm scripts with make targets

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Given some changes in behaviour in NPM 7, this PR replaces all `npm run` scripts with `make` targets.

### CODE REVIEW

**Comment by mwest1066** [comment]
Looks great to me (other than the CI failure). @nicknytko or @tdy, can someone verify that this works under WSL2 and archlinux? You should be able to use this branch with a current `prairielearn/prairielearn` docker image. That is, with this branch checked out, it should work fine if you do:
```
docker run -it --rm -p 3000:3000 -v $PWD:/PrairieLearn prairielearn/prairielearn
```

**Review by mwest1066 — APPROVED** [review]

**Comment by tdy** [comment]
> 
> 
> Looks great to me (other than the CI failure). @nicknytko or @tdy, can someone verify that this works under WSL2 and archlinux? You should be able to use this branch with a current `prairielearn/prairielearn` docker image. That is, with this branch checked out, it should work fine if you do:
> 
> ```
> docker run -it --rm -p 3000:3000 -v $PWD:/PrairieLearn prairielearn/prairielearn
> ```

Works for me in both Arch and WSL2. I did a `docker pull` and `npm ci` before running that command on f879f8a of `make-scripts`.

**Comment by nicknytko** [comment]
Also works for me on arch!

**Review by nicknytko — APPROVED** [review]

**Comment by mwest1066** [comment]
Awesome, thanks @tdy and @nicknytko!

**Pull request merged**
