### PR TITLE
Instructor controls for force-breaking open variants of questions

### PR DESCRIPTION
**Pull request by astrosticks**
# Summary

See #3216. Adds buttons next to each question in the `instructorAssessmentQuestions` and `instructorAssessmentInstance` pages to let instructors force students to generate new variants of questions on a per-question or per-student/group basis.

# Screenshots

image

# To-do
- [x] Add `broken_by` and `broken_at` columns to `variants` table. `broken-at` replaces `broken`.
    - [x] Update `sprocs/variants_insert` to handle boolean `broken` param from `lib/question.js`
    - [x] `lib/question.js:1014` Modify `broken` if necessary
    - [x] `lib/question.js:1277` Modify `broken` if necessary
    - [x] `question-servers/freeform.js` Modify `broken` if necessary throughout file
        - See `tests/helperQuestion.js:123`
- [x] When a variant is broken, display it in the `instructorAssessmentInstance` log.
- [ ] Integration tests
- [ ] Bug: New variants generate whenever a student reloads an instance question page.
    - [x] Fix bug
        - `studentInstanceQuestionHomework.js:99` calls `question.getAndRenderVariant`, which calls `_ensureVariantWithClient`.
            - [x] Verify that `instance_question_id != null`
            - [x] Check why `sqldb.callWithClient::instance_questions_select_variant` is returning null*
    - [ ] *Double-check other modified SQL to verify that logic hasn't been inverted: `broken = true == broken_at IS NOT NULL` and `broken = false == broken_at IS NULL`

### CODE REVIEW

**Comment by astrosticks** [comment]
I have reviewed and hereby sign the CLA

**Comment by astrosticks** [comment]
@mwest1066 When an instructor breaks a question and it gets logged in the student's assessment instance overview, do you want the user field in the log to display the instructor's real user_id or their effective user_id?

**Comment by echuber2** [comment]
How are grades handled if a question is marked as broken? If students have already submitted and earned (possibly unwarranted) points, does it revoke those?

**Comment by astrosticks** [comment]
@echuber2 I believe that if a student has submitted a response and received credit, then that variant should be marked as closed: https://prairielearn.readthedocs.io/en/latest/question-flow.png, and therefore, won't get caught by these actions. The case where we would want to see this used is when students currently have open variants for questions that they shouldn't receive credit on / shouldn't try to complete. The instructor would push changes to the questions, sync the course, and then use one of these actions to make sure that students don't see outdated variants.

**Comment by astrosticks** [comment]
@echuber2 oops, sorry, ignore my other reply. I think I misunderstood you. This shouldn't revoke points, since we don't know why the instructor might have wanted to mark active variants as broken.

**Comment by eliotwrobson** [comment]
@mwest1066 Is this feature still in progress? This would be useful to us in 374, and if it's not being actively worked on, we can have someone from our team pick this up.

**Comment by nwalters512** [comment]
@eliotwrobson I don't believe David is actively working on this PR anymore. It'd be great to have one of y'all take it over the finish line!

**Comment by eliotwrobson** [comment]
@nwalters512 Sounds good! Have a couple of follow-up questions to see things are at before we get started, will message on slack.

**Comment by nwalters512** [comment]
I'm planning on reviving this PR. I think we're going to have to deploy this in multiple parts:

- Add the `broken_at` column and dual-write to that when inserting broken variants.
- Add a batched migration to set `variants.broken_at = variants.date WHERE variants.broken = TRUE`.
- Allow the batched migration to run to completion in production environments.
- Add the `broken_by` column and implement the UI for force-breaking open variants.

**Comment by mwest1066** [comment]
> I'm planning on reviving this PR. I think we're going to have to deploy this in multiple parts:

I agree that this will need a two-phase deploy with a batched migration in the middle. Your plan sounds reasonable and I can't think of anything simpler.

**Comment by nwalters512** [comment]
@astrosticks it looks like you made some commits without an email, so unfortunately our CLA requirement will prohibit us from merging this PR. Given that you did sign the CLA though, it should be fine for us to lift all this work into a new PR. Thank you for all your work on this! I'm excited to be taking it over the finish line.

**Comment by nwalters512** [comment]
Closing in favor of #8889.

**Comment by astrosticks** [comment]
> @astrosticks ...our CLA requirement will prohibit us from merging this PR...

Thanks for letting me know so I can look out for that in the future 😊

**Pull request closed without merging**
