### PR TITLE
Match case of jsPlumb with file name

### PR DESCRIPTION
**Pull request by lotrfan**
Fixes loading on case-sensitive filesystems.

### CODE REVIEW

**Comment by mwest1066** [comment]
Thanks! But how did this ever work on Linux? I think it was working on Linux because @tnip was using it for CS 421 (or so I assume).

**Comment by lotrfan** [comment]
No idea; I was also confused at first since it works in prod, but apparently everything is bundled in a single file.

**Comment by mwest1066** [comment]
Ah, excellent point! Of course this is the reason. It never tries to access jsplumb as an actual file on disk on the prod server.

I really hate OS X for being case insensitive.

**Comment by tnip** [comment]
Thanks for fixing my hack; much appreciated!

**Pull request merged**
