### PR TITLE
Improved autograder security

### PR DESCRIPTION
**Pull request by nwalters512**
This wipes environment variables after we cache them in memory so that enterprising students can't grab CSRF tokens, job ids, etc.

### CODE REVIEW

**Comment by mwest1066** [comment]
@nwalters512 what are your thoughts on converting this to create a clean new ENV and passing it to the client process with `subprocess.Popen` rather than `subprocess.call`? If you'd rather just merge as-is then I'm fine with that.

**Comment by nwalters512** [comment]
I don't have any strong opinion either way, but doing it that way would probably be better in the long run so we don't have to remember to explicitly delete new variables.

**Comment by mwest1066** [comment]
I guess it's mainly a question of whether you have time to do it now? If not, I'll just merge this as-is. Not pressuring you, just asking.

**Comment by nwalters512** [comment]
Yeah, I don't think I'll have time today. We can add that to a list of nice-to-haves to be done later :)

**Comment by mwest1066** [comment]
@JParisFerrer when I run with this branch on `fibonacciExternalUpload` I get:

```
error: No environment was specified for externally graded question.
```

**Comment by mwest1066** [comment]
Closing this PR as it's now invalidated by PrairieGrader and associated infrastructure.

**Pull request closed without merging**
