### PR TITLE
New Question Reset

### PR DESCRIPTION
**Pull request by EricJ19**
Feature to allow question to reset, building on [PR](https://github.com/PrairieLearn/PrairieLearn/pull/3552).

Replaces #6504 by making commit history cleaner.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
Hi, @EricJ19 , thank you for your contribution. Just to let you know, you usually don't need to worry about making the commit history cleaner, as we typically merge the PR using a [squash method](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits), so your entire PR would be converted to a single commit in master.

**Comment by EricJ19** [comment]
Thank you for the note and help @jonatanschroeder. That makes a lot of sense. Also, I was trying to make it also easier for reviewers to view but indeed it doesn't seem necessary.

**Comment by nwalters512** [comment]
@EricJ19 would you still like to see this PR through?

**Comment by EricJ19** [comment]
> @EricJ19 would you still like to see this PR through?

Hi Nathan, sorry this PR got a little stale. For now, I unfortunately wont be following up on this as I am prioritizing CS374 PraireLearn development. But, I am also very happy to help if this gets picked up by someone else and I can also potentially continue to work on this later if no one picks this up.

**Comment by jeffgerickson** [comment]
Bump.  We need this ASAP.

**Comment by nwalters512** [comment]
I'm closing this in favor of #3552, which I'll use as a foundation for future work. Note that I probably won't merge that PR directly, as it needs to be implemented and deployed in multiple sequential steps.

**Pull request closed without merging**
