### PR TITLE
Fix unawaited promise on course instances page

### PR DESCRIPTION
**Pull request by Nakasu-ksm**
When PrairieLearn cannot found course Path in /pl/course/:course_id(\d+)/course_admin/instances
PrairieLearn will crash.

### CODE REVIEW

**Comment by Nakasu-ksm** [comment]
also see #9941

**Comment by nwalters512** [comment]
Please reopen #9941 and separate your changes into these two PRs. They're very different and should be reviewed and merged separately.

**Comment by Nakasu-ksm** [comment]
> Please reopen #9941 and separate your changes into these two PRs. They're very different and should be reviewed and merged separately.

I reopen the #9941 if I need close this and submit new PR with separate change? Thank you!

**Comment by nwalters512** [comment]
No need for a third PR, just remove the changes to `apps/prairielearn/src/ee/auth/saml/index.ts` from this one.

**Comment by Nakasu-ksm** [comment]
> No need for a third PR, just remove the changes to `apps/prairielearn/src/ee/auth/saml/index.ts` from this one.

Thank you so much. Already deleted the changing of apps/prairielearn/src/ee/auth/saml/index.ts from this PR.

**Review by nwalters512 — APPROVED** [review]

**Pull request merged**
