### PR TITLE
Add tzlocal as a python library under core

### PR DESCRIPTION
**Pull request by coatless**
New dependency of `rpy2`

### CODE REVIEW

**Comment by mwest1066** [comment]
I’m not necessarily opposed to adding this library, but for my own curiosity, why do you want it? The local timezone is UTC on the PL servers. If you just want the TZ database then `pytz` might be what you want?

**Comment by coatless** [comment]
@mwest1066 it's an "optional hard" dependency for `rpy2` when using `pandas`

c.f. https://bitbucket.org/rpy2/rpy2/issues/458/tzlocal-dependency

**Comment by mwest1066** [comment]
@coatless can you rebase this to current master to fix the tests?

**Comment by coatless** [comment]
@mwest1066 this is good to go!

**Pull request merged**
