### PR TITLE
fix: Ignore deleted groups in assessment statistics calculation

### LINKED ISSUE #9871: Console error on assessment statistics page in obscure scenarios
image

I haven't investigated the source, but this is a local testing assessment, groupwork enabled, and all groups have been deleted (though the assessment instances remain). The only instance with a non-deleted group is one where the only user is a staff member.

### PR DESCRIPTION
**Pull request by jonatanschroeder**
As I was looking into #9871, I noticed that the described scenario (all groups were deleted, other than a group with staff only) was a situation where the stats should have listed "no student data", as there is no student in that scenario that has any active assessment that should be included in the stats. None of the students had an active group. So this PR changes the stats calculation (including duration) to only apply to non-deleted groups.

Also update query to avoid an unnecessary `OR` restriction in the `users` condition.

One minor issue with this change is that it will only take effect once the assessment stats are recalculated, which only happens if some assessment instance is updated. I'm not sure if this warrants a forced recalculation at this point, thoughts? I don't think this is needed, but I want to raise it to make sure this is considered.

Fixes #9871.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
Another issue as I'm thinking of this: At this point, stats are only updated if any assessment instance is modified, but as far as I can tell, deleting a group will not cause the assessment instance modified_at column to be modified. Should the stats also be recalculated if a group is deleted? This could be done with a query that selects groups in the current assessment that have a deleted_at more recent than the assessment's `statistics_late_updated_at` (or ), as an extension to this query:
https://github.com/PrairieLearn/PrairieLearn/blob/8032638ad907e9c322f2e69fd83131c83e572594/apps/prairielearn/src/lib/assessment.sql#L126-L139

Group creation should not be a problem, since a the creation does not cause an assessment instance to be created right away. Group composition change may, though: if a group with an active assessment instance adds or removes a member, this affects the statistics. Should these be considered? These might be a bit trickier to identify, it might require a filter on the group_logs table.

**Comment by nwalters512** [comment]
Could we instead update `assessment_instances.modified_at` in more cases? This _could_ be undesirable in the context of https://github.com/PrairieLearn/PrairieLearn/issues/9392, where we plan to show `modified_at` on the "Students" tab, though maybe we do also want to consider an assessment to be "modified" when group membership changes?

Alternatively, we could add more tracking columns to avoid touching `modified_at` in case we decide that that's important to do. For instance, `group_updated_at` or (bikeshed name) `statistics_need_updating_after`.

Note that https://github.com/PrairieLearn/PrairieLearn/pull/6656 specifically added an index on `(assessment_id, modified_at)` so that we can very cheaply determine if statistics need updating. I'd very much like to retain that property if possible.

**Comment by jonatanschroeder** [comment]
> Could we instead update `assessment_instances.modified_at` in more cases? This _could_ be undesirable in the context of #9392, where we plan to show `modified_at` on the "Students" tab, though maybe we do also want to consider an assessment to be "modified" when group membership changes?

That is a good point, and I'd argue that modifying the group composition should count as a modification of the assessment instance. It seems to me that this only needs to be done in [the groups.sql library](https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/src/lib/groups.sql), since #9095 and #9448 have already migrated all group update processes to this library.

> Alternatively, we could add more tracking columns to avoid touching `modified_at` in case we decide that that's important to do. For instance, `group_updated_at` or (bikeshed name) `statistics_need_updating_after`.

That's an option, but I'd argue more towards `modified_at`, mostly to avoid adding too many separate date/time columns, but also to reuse the index that you mentioned.

**Comment by jonatanschroeder** [comment]
8bb04e7 updates `modified_at` if a user is added or removed from a group, or if the group is deleted (individually or in mass). Group creation does not have an active assessment at the time of creation, so does not require an update. For similar reasons, group membership updates before the assessment instance is created do not trigger a stats update, and that is expected, since stats are not affected by groups without an assessment instance.

Role changes do not affect statistics so I have not updated `modified_at`, but if there is a reason to update it as well (unrelated to statistics) I can do the change.

This PR does not include a migration that updates stats (or `modified_at`) for existing assessments, I'm assuming that's ok.

**Review by nwalters512 — APPROVED** [review]

**Pull request merged**
