### PR TITLE
WIP Make PL/PS linkage visible in PL

### PR DESCRIPTION
**Pull request by trombonekenny**
Adds links to the instructor assessment list and individual assessment (access rules) that verify an assessment's access control rules encompass the exam date ranges in PrairieSchedule.

lib/plps-utilities.[js,sql] are the shared code between both PL and PS. There's also a sproc. Right now I've been keeping the code updated in both repos.

### CODE REVIEW

**Comment by nwalters512** [comment]
Unrelated to content of the PR, but is there any other code that's common to PL and PS? I know our sqldb module is also similar. If there's enough, it might be worth extracting the shared stuff into an npm package.

**Comment by mwest1066** [comment]
Yeah, there is definitely stuff that could be pulled out into separate shared packages. sqldb is probably the most obvious one. There has also been talk about moving PS to the PL migration code.

**Comment by trombonekenny** [comment]
PS is pretty much an old copy of PL, in terms of libraries, methodologies, etc. A big refactor would be to pull out the common bits and make some sort of a PrairiePackage that streamlines the functionality. But I don't also see the point in doing that until 1) we do more active development in the base shared pieces (sqldb) and want an independent place to track it or 2) we have a new Prairie_____ project where we want to start fresh.

Standardizing things like logging, debugging, initialization, database changes would be nice. PS and PL both have different advances that could be brought back to each other and shared. But that seems big scope.

For this, I tried to put anything that depended on data not already in that project's tables or methods into the library so at least we can edit in one place. For now I've been keeping the "master" in the PS branch and copying these lib files over to my PL branch.

**Comment by trombonekenny** [comment]
I think this is ready for review and merge. I'd feel better if there were some test cases around it, but I'm not sure what I'd do with them.

**Comment by mwest1066** [comment]
This has now been implemented.

**Pull request closed without merging**
