### PR TITLE
Unsubmitted enhancements

### PR DESCRIPTION
**Pull request by lotrfan**
Open to suggestions for colors... I'm not really a fan of the current ones, but they are based on the bootstrap 'warning' colors (at least for the buttons; I didn't think the `.panel-warning` colors were dark enough, so I adjusted those slightly.)

I think it would also help to have some sort of textual indication show up when colors change. (Maybe only the first time.)

2016-04-05t00 00 01-05 00

### CODE REVIEW

**Comment by tnip** [comment]
I'm inclined to say the buttons in the sidebar on the right should stay the same - if anything, I think the Save Answer button should change colors since we want to make it clear that that's the action item they need to take care of.

Mayhaps... make the question background pastel red, make the header a darker pastel red (pink?), and leave the button as-is assuming we get nav-off alerts built in?

**Comment by mwest1066** [comment]
Nice! This code hack was less disgusting than I'd been imagining :-)

I like the basic concept, but I agree that the specific colors/lack-of-text could do with some tweaking.

Some specific suggestions:

1. Use red colors to fit with the red color of the "unsaved" label. Or change the unsaved label to be orange to match the warning color. I'm not fussed either way. I think the unsaved label currently turns "warning" color while it's in the process of saving, but this could be changed to gray or something to not conflict.

2. Fix the saved/unsaved label in the right-hand panel (the one titled "Question #N"). This seems to not be updating correctly at the moment as the answer is edited.

3. I feel like coloring the whole question panel is a bit extreme (especially for numeric-answer questions). How about coloring the right-hand panels instead? These are still pretty large, so should be very noticeable, and they are also where the prev/next/overview buttons are located that will navigate away from the current question. I wouldn't necessarily be opposed to turning all the right-hand column buttons red as well.

4. In addition to (3), we could also have a class like "unsaved-warning" that question authors could attach to elements in question.html that would then get the alert colors as well. I'm thinking that the file questions could have this class on the drop zone, for example.

**Comment by lotrfan** [comment]
For 2, is the label in the sidebar supposed to be synced up with the label by the 'save' button? They both do changed to 'saved' when it's saved.

In regards to 4... I wasn't really quite sure the best styles to have for that---split it up into various `unsaved-warning-bg`, `unsaved-warning-border`, `unsaved-warning-show`, etc? It's not as convenient as a single class, but you can use something like this, too:
``` html
<style>
.dirty .some-class {
// whatever you want
}
</style>
```

I added various parts of the other bullets. Everything is now the 'warning' color**. I also added information on when the last save happened.

Let me know if you want me to squash into fewer commits.

2016-04-09t00 54 59-05 00

** @kevinwang has expressed some concern about the use of red in relation to exams.

**Comment by kevinwang** [comment]
Moment supports the functionality of timeago with `fromNow()`. Is there a reason we're using timeago here?

**Comment by lotrfan** [comment]
timeago auto-updates the DOM as time passes

**Comment by mwest1066** [comment]
Proposal: only change the main question panel, use dark yellow color to match the label color (and `panel-warning` is too pale to be noticed). Also have the `dirty` class so that specific questions types can add more noticeable warnings (`MultiFile` in particular).

**Comment by lotrfan** [comment]
Restyled and rebased; let me know if it looks good and I can squash.

https://dl.jtolar.net/pl-unsubmitted.mp4

**Comment by mwest1066** [comment]
Looks good to me. Squashed and rebased on current (or near) master would be great.

**Comment by mwest1066** [comment]
Closing this old PR

**Pull request closed without merging**
