### PR TITLE
Workspace reboot nav fix: avoid failed check for 'running' workspace

### LINKED ISSUE #10716: Rebooting workspaces locally crashes the PL server
I'll try to put together a better reproducible example and narrow down whether this is "just me" later today, but in case anybody else is noticing it already, hitting "Reboot" or "Reset" on a workspace in local testing is just crashing everything:

```
info: Workspace host ready
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
info: Launching workspace-1-1 (useInitialZip=true)
info: Not pulling docker image
```

(Then I do stuff in the workspace and click "Reboot":)

```
file:///PrairieLearn/apps/prairielearn/dist/server.js:265
                throw new error.HttpStatusError(404, 'Workspace is not running');
                      ^

HttpStatusError: Workspace is not running
    at router (file:///PrairieLearn/apps/prairielearn/dist/server.js:265:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getTarget (/PrairieLearn/node_modules/http-proxy-middleware/dist/router.js:14:21)
    at async HttpProxyMiddleware.applyRouter (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:110:29)
    at async HttpProxyMiddleware.prepareProxyRequest (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:97:13)
    at async HttpProxyMiddleware.handleUpgrade (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:62:44) {
  status: 404
}
```

There's probably just something weird with my setup that is causing it to not enumerate these properly. Creating a new variant and starting it up does work, though.

### PR DESCRIPTION
**Pull request by echuber2**
Fixes #10716 

Working locally (at least), after rebooting a workspace, it temporarily has state `'stopped'`, which causes nav to fail as this expects `'running'`. (Or, when resetting, the state is temporarily `'uninitialized'`.) Also the database query failure crashes the PL server hard (but not the workspace host)! This doesn't seem to be a problem in deployment for some reason, but I don't know why not. Maybe the sequence of updates to the workspace state happen more quickly in deployment.

This PR sets the state to `'running'` sooner and also removes the search criterion for `'running'` during the nav lookup. Actually either measure alone solves the problem, it seems. Is it better to only use one fix or the other? I would think that maybe it's sufficient to just remove the search criterion, and if the workspace still isn't running when the page loads, let whatever error message appear to the user naturally.

### CODE REVIEW

**Comment by echuber2** [comment]
Something this PR doesn't address is why this nav failure crashes the PL server hard. It seems like that shouldn't be happening anyway.

**Comment by echuber2** [comment]
> Something this PR doesn't address is why this nav failure crashes the PL server hard. It seems like that shouldn't be happening anyway.

I found something interesting by first reverting to master and ignoring the workarounds presented in the PR, and then experimenting with throwing an error on purpose in the middleware router:

```javascript
    // in server.js...
    router: async (req) => {
      throw new Error('hi');
    // ...
```

Load up a workspace and:

```
error: Error page {"id":"YYQDOCOIUMCI","msg":"hi","referrer":"http://localhost:3000/pl/workspace/1","stack":"Error: hi\n    at router (/PrairieLearn/apps/prairielearn/src/server.js:344:13)\n    at Object.getTarget (/PrairieLearn/node_modules/http-proxy-middleware/dist/router.js:14:27)\n    at HttpProxyMiddleware.applyRouter (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:110:42)\n    at HttpProxyMiddleware.prepareProxyRequest (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:97:24)\n    at HttpProxyMiddleware.middleware (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:21:59)\n    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/src/instrumentation.ts:198:27)\n    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:328:13)\n    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9\n    at param (/PrairieLearn/node_modules/express/lib/router/index.js:365:14)\n    at param (/PrairieLearn/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:421:3)\n    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)\n    at <anonymous> (/PrairieLearn/apps/prairielearn/src/server.js:413:7)\n    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/src/instrumentation.ts:198:27)\n    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)","status":500}
Error: flash() must be called within a request
    at flash (/PrairieLearn/packages/flash/src/index.ts:31:11)
    at FlashMessages (/PrairieLearn/apps/prairielearn/src/components/Navbar.html.ts:268:9)
    at Navbar (/PrairieLearn/apps/prairielearn/src/components/Navbar.html.ts:101:64)
    at ErrorPage (/PrairieLearn/apps/prairielearn/src/pages/error/error.html.ts:52:11)
    at default (/PrairieLearn/apps/prairielearn/src/pages/error/error.ts:38:5)
    at Layer.handle_error (/PrairieLearn/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:326:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:346:12)
    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)
    at sentryErrorMiddleware (/PrairieLearn/node_modules/@sentry/node/src/integrations/tracing/express.ts:127:60)
    at Layer.handle_error (/PrairieLearn/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:326:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:346:12)
    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)
```

The rendered page only shows the second part:
pl-flash-error

In `Navbar.html.ts`, if I edit `FlashMessages()` to just return ```return html``;``` before ever calling `flash(...)`, then the PL frame is able to at least render the error message as normal.

What's really weird is that this other, non-crashing error behavior only happens if I explicitly force an error in that router function. The crash only seems to happen if the error is thrown within the conditional. I tried changing the message too, to see if there was some weird interaction with the Sentry beforeSend handler:

```js
      // throw new error.HttpStatusError(404, 'flash error');
      if (result.rows.length === 0) {
        throw new error.HttpStatusError(404, 'crash bug');
        // throw new error.HttpStatusError(404, 'Workspace is not running');
      }
```

Now if I:
- Uncomment the "flash error" line and just start up the Jupyter workspace, I get the flash error message.
- Comment out the "crash bug" line and start up the Jupyter workspace, after it loads successfully the first time, hit Reboot, and (with high probability) the crash bug happens.

I suspect the crash bug might somehow be related to https://github.com/chimurai/http-proxy-middleware/pull/823 and the strange intermittance based on the conditional might be due to async behavior, websocket issues, or timing, or something.

I still think this PR is worthwhile, since it prevents the false negative database query from throwing an error message at all. But since other errors can theoretically happen in this middleware, if I could suggest other workarounds here, it would be to fix whatever is preventing the flash error message feature from working in this context, and then (to avoid the crashbug) still _avoid_ throwing an error from this context at all, and instead route to a special "fake" error page as a 200 success.

**Review by nwalters512 — CHANGES_REQUESTED** [review]
This change does not make sense to me. We _very intentionally_ do not mark a workspace as "running" until it completes health checks and gets assigned a hostname:

https://github.com/PrairieLearn/PrairieLearn/blob/337d56b0e285769c8634775f0b25494be251d892/apps/workspace-host/src/interface.js#L955-L963

We also definitely should not route workspace traffic to a workspace that isn't running, as that traffic would go to a host/container/port that doesn't exist, or worse, a host/container/port that _does_ exist but that is serving a different workspace.

I agree with the assessment that the crash is likely due to https://github.com/chimurai/http-proxy-middleware/pull/823j. I followed up with the maintainer there to see what we'll need to do.

**Comment by nwalters512** [comment]
I'm going to close this to keep the PR list clean. We can discuss the issue and potential fixes back on #10721.

**Comment by echuber2** [comment]
I can see that faking the 'running' state early is not a great solution (I expected to walk that part back). One thing I still don't understand is why navigating to a workspace with the same ID, but that is not 'running', would result in serving a different (someone else's? _running_?) workspace. If that's true, it sounds like the security model for routing workspaces has other vulnerabilities. I was hoping that speculatively navigating to the workspace under the assumption that it would be running and simply letting the nav fail outside of this context would at least be preferable, but instead, I've made a new PR that retries the query for a few seconds.

**Comment by nwalters512** [comment]
There are no routing vulnerabilities. Your PR would have _introduced_ routing vulnerabilities. We currently maintain the property that the tuple `(hostname, port)` is unique among running workspaces, so there cannot be collisions. This does _not_ hold for workspaces that are not running. So, there is a small but real possibility that a running and non-running workspace may share the same hostname and port. This is only a problem if we try to use the hostname/port of a non-running workspace to route traffic, which is precisely what your PR did.

**Comment by echuber2** [comment]
Thank you for the clarification.

**Pull request closed without merging**
