### PR TITLE
Add score only assessments

### PR DESCRIPTION
**Pull request by Kieran-Weaver**
This pull request adds the `scoreOnly` flag to `assessmentInfo.json`, which specifies that an assessment is only for score upload. As described in issue #3606, score only assessments cannot be attempted by students. Instead, when an instructor uploads scores, assessment instances are created automatically if they do not already exist.

@jonatanschroeder 

TODO:

- [ ] Unit tests
- [ ] ReadTheDocs Documentation

### CODE REVIEW

**Review by jonatanschroeder — COMMENTED** [review]
The feature you created, instead of making an assessment "score only", makes it so a new instance is created on upload when one doesn't exist. I'd imagine a score-only assessment would need a bit more thought (e.g., possibly the ability to have no questions, and some further thoughts on how to handle cases where students open this kind of assessment, before or after a grade is pushed). Maybe having this feature in combination with the submittable feature that Eugene has submitted may make more sense, but I believe in this case it may be better to focus on what this feature actually does. This means replacing "scoreOnly" with "autoInstanceCreation" or something similar. Thoughts?

For the sprocs: 

* for the arguments in the sprocs, instead of user_uid I believe it would be more generic to make it user_id, and have the caller obtain the user_id instead;
* dates in general come from SQL, not from JS. Instead of date as an argument, use SQL date expressions like `current_timestamp`;
* instead of passing `score_only` as an argument, note that you already fetch `group_work` and `mode` from the assessment, might as well fetch the `score_only` flag from there as well.
* Uploads of group assessments are typically based on the group name, not on one of the students' UIDs. Based on the code above it would make sense for the user ID to also have a group ID in case of group work.

**Comment by Kieran-Weaver** [comment]
Renaming "scoreOnly" makes sense, would "createInstancesOnUpload" be a better name? I don't know if something like "autoInstanceCreation" would be intuitive to use.

**Comment by jonatanschroeder** [comment]
Maybe createInstanceOnGrading? Upload may be too restrictive if we want to allow other types of manual grading later.

**Comment by Kieran-Weaver** [comment]
createInstanceOnGrading sounds like a better name. For the sprocs, I used the user id for group assessments because `assessment_instances_insert` takes a user id regardless of `group_work`. Is there a better way to create group assessment instances?

**Comment by jonatanschroeder** [comment]
> For the sprocs, I used the user id for group assessments because `assessment_instances_insert` takes a user id regardless of `group_work`. Is there a better way to create group assessment instances?

Good point. Let's keep it like this for now and discuss how to handle group assessments later. I imagine the best option would probably require more thought, potentially creating a group for the user if one does not exist.

**Comment by nwalters512** [comment]
@Kieran-Weaver would you still like to see this PR through?

**Comment by Kieran-Weaver** [comment]
No, I'm not working on this anymore. Sorry!

**Pull request closed without merging**
