### PR TITLE
Added touch support for pl-order-blocks

### PR DESCRIPTION
**Pull request by SethPoulsen**
Resolves https://github.com/PrairieLearn/PrairieLearn/issues/4938 and part of https://github.com/PrairieLearn/PrairieLearn/issues/4912. 

It would be nice if someone else could test this for me. Its not too bad, just: 

1. Clone my branch
2. Run `npm ci` to pull the new dependency
3. Run prairielearn on your machine, overriding the PrairieLearn folder in the docker container with the new version
4. Make sure you have a phone/tablet on the same network as the computer you are running PL on, then open `http://<your computer's IP address>:3000/pl/course_instance/3/instructor/question/95/preview` to open the example question and try it out.

edit: I only tested on my Android phone, if someone could test with iOS, that would be nice though since I'm just using a standard node package I don't think it should be an issue.

### CODE REVIEW

**Comment by SethPoulsen** [comment]
@nwalters512 I added the new dependency by `npm i --save jquery-ui-touch-punch` and then I committed the changes that the command made to `package.lock.json`, was that the right thing to do? I've never had to deal with this thing before.

**Comment by SethPoulsen** [comment]
Thanks @jonatanschroeder 

Ya, that happened on my phone too. We should make a new issue for that. I think its probably fine on tablets.

**Comment by SethPoulsen** [comment]
I made a new issue for that here: https://github.com/PrairieLearn/PrairieLearn/issues/4955

To be clear, I did test with my phone _before_ making the change to support touch, and this layout issue is definitely unrelated/not cause by this change.

**Comment by jonatanschroeder** [comment]
> I made a new issue for that here: #4955 (I can upload my own screenshot if you object to me using yours)
> 
> To be clear, I did test with my phone _before_ making the change to support touch, and this layout issue is definitely unrelated/not caused by this change.

Go for it, it doesn't have anything revealing (part of one of my questions, but nothing that gives away any information).

**Pull request merged**
