### PR TITLE
Fix questions page case where no instance is available

### LINKED ISSUE #4673: Course "Viewer" with no course instance access cannot view Questions
Reported by Eric Larson.

This occurred in XC 101 where users default to have `course_role = Viewer` and no course instance access.

pl_error_xc101_demo_access

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Fixes issue listed recently on Slack.

Fixes #4673

### CODE REVIEW

**Comment by mwest1066** [comment]
Hahaha, #4674

**Comment by jonatanschroeder** [comment]
Different approaches. Which do you prefer? Should it remain NULL?

**Comment by mwest1066** [comment]
> Different approaches. Which do you prefer? Should it remain NULL?

I tend to think it's cleaner to always have `locals.course_instances` be an array, so we don't have to check whether it's NULL before every use?

**Comment by mwest1066** [comment]
Can you reproduce the bug? I'm failing to repro locally in XC 101.

**Comment by mwest1066** [comment]
> Can you reproduce the bug? I'm failing to repro locally in XC 101.

Oh sorry, I can repro just fine. And I confirmed that #4674 fixes the problem.

**Comment by mwest1066** [comment]
> > Different approaches. Which do you prefer? Should it remain NULL?
> 
> I tend to think it's cleaner to always have `locals.course_instances` be an array, so we don't have to check whether it's NULL before every use?

Which fix do you think is cleaner?

**Comment by jonatanschroeder** [comment]
> I tend to think it's cleaner to always have `locals.course_instances` be an array, so we don't have to check whether it's NULL before every use?
> 
> Which fix do you think is cleaner?

We already check before use, at least where I could find, e.g.:

https://github.com/PrairieLearn/PrairieLearn/blob/ec5d41c856feb0c47328b88b63938feadb1199f1/pages/partials/navbarInstructor.ejs#L71

The line above should work as expected anyway, so I don't have a problem with either approach. We could even use both 😄  I'll review yours, it's actually a bit cleaner. Closing this one.

**Comment by mwest1066** [comment]
> We could even use both 😄 I'll review yours, it's actually a bit cleaner. Closing this one.

Sounds good 😄

**Pull request closed without merging**
