### PR TITLE
fix: Improve security of cookies

### PR DESCRIPTION
**Pull request by nwalters512**
This change ensures that our authentication cookie won't be accessible to client-side JavaScript, which is a security best practice (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).

### CODE REVIEW

**Comment by mwest1066** [comment]
1. Maybe we should also set `Secure: true` on the cookies? This has almost no impact, but I think it can't hurt and could potentially mitigate a MITM intercept where the user is tricked into visiting the `http` version of the site.

2. Any reason that we don't also set `HttpOnly` in the two places below? I realize that they are much less important than the `pl_authn` cookie, but it also can't hurt? Here: https://github.com/PrairieLearn/PrairieLearn/blob/2f3b359987bebf00d45a8c32d58e3b302d117c4a/middlewares/authzWorkspaceCookieSet.js#L17 and here: https://github.com/PrairieLearn/PrairieLearn/blob/435580fee3490bc2fd1814f0d2ef77270f3fd9cb/pages/authPassword/authPassword.js#L22

**Review by mwest1066 — APPROVED** [review]

**Comment by nwalters512** [comment]
@mwest1066 changes made in e3c596e - LMK if they look good to you!

**Review by mwest1066 — APPROVED** [review]

**Comment by trombonekenny** [comment]
We should confirm things still work okay for local development, or other places where the cookies and https aren't necessarily a given. That's a part of my #1724, changing devMode from "the default" to one option of many, which would mean the cookies have to work. Sessions would also incorporate where we're currently setting a few different cookies, I think.

**Comment by nwalters512** [comment]
@trombonekenny cookies should indeed still work locally; see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies:

> A cookie with the `Secure` attribute is only sent to the server with an encrypted request over the HTTPS protocol. It's never sent with unsecured HTTP **(except on localhost)**

**Comment by trombonekenny** [comment]
@nwalters512 It's not out of character for me to point Windows and MacOS at my Linux local dev of PL. It's okay that this is broken, I guess, because we'll revisit all of it with `express-session` and be able to set all of those cookie parameters in one place.

**Comment by trombonekenny** [comment]
Or I'll point my local PL behind ngrok so the other clients get https. I'm just warning that cookies are tricky. :)

**Pull request merged**
