### PR TITLE
Fix alignment of manual grading footnote

### PR DESCRIPTION
**Pull request by tdy**
left=old, right=new

image

### CODE REVIEW

**Comment by mwest1066** [comment]
Do we want to reverse the order of the text and button? It somehow looks weird to me having the button be in the middle of the footer.

**Comment by nicknytko** [comment]
> Do we want to reverse the order of the text and button? It somehow looks weird to me having the button be in the middle of the footer.

Agreed. @tdy can we see a screenshot of this?

**Comment by tdy** [comment]
> Agreed. @tdy can we see a screenshot of this?

image

**Comment by nicknytko** [comment]
> > Agreed. @tdy can we see a screenshot of this?
> 
> image

That looks way better imo

**Comment by tdy** [comment]
Agreed. The other thing I was considering was keeping both buttons but graying out and disabling the grade button.

**Comment by mwest1066** [comment]
I think that this now looks great. I think graying out "Grade" isn't needed given that we've got the explanatory text.

**Comment by trombonekenny** [comment]
lgtm

**Pull request merged**
