### PR TITLE
Typo in example note of "What To Tell Students"

### PR DESCRIPTION
**Pull request by luema**
There is a typo in the example piazza note under "What to tell students":
```...your point total with never go down!``` -> ```...your point total will never go down!```

### CODE REVIEW

**Comment by luema** [comment]
I have reviewed and hereby sign the CLA
- SK

**Comment by luema** [comment]
recheck

**Comment by nwalters512** [comment]
@luema thanks for the PR! You'll have to type the CLA signature without the trailing `- SK` for it to accept it - the bot is perhaps a little too strict 🙂

**Comment by luema** [comment]
recheck

**Pull request merged**
