### PR TITLE
Add support for changing params in parse phase

### PR DESCRIPTION
**Pull request by jonatanschroeder**
In this code we add support for the `parse(data)` function in server.py to change the value of params. This allows instructors to update incorrect values of params on new submissions for old variants before grading takes place, which has been a relatively common issue recently. Some common examples of how this can be used:

* Regular case: update the values of parameters used in the answer and submission panel based on values submitted by the student.
* Fixing potentially incorrect values of Python grader parameters (`names_from_user`, `names_for_user`) after the variants have been updated.
* Fixing values of some parameters associated to elements that initialize them on generate/prepare if the question has been updated.
* Fixing values of `_workspace_required_file_names` if `gradedFiles` are updated.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
Note: this does not affect v2 questions because v2 questions don't have a parse phase.

https://github.com/PrairieLearn/PrairieLearn/blob/e1f6193f65a574cc6cb99a53bfb2280d21c050d2/apps/prairielearn/src/question-servers/calculation-subprocess.js#L108-L109
https://github.com/PrairieLearn/PrairieLearn/blob/e1f6193f65a574cc6cb99a53bfb2280d21c050d2/apps/prairielearn/src/question-servers/calculation-subprocess.js#L138-L149

**Review by nwalters512 — APPROVED** [review]
I assume you've tested this and it works correctly.

**Comment by nwalters512** [comment]
One more thing: we've implemented this incorrectly in the past, at least when it comes to things in the `grade()` function. Might be worth checking https://github.com/PrairieLearn/PrairieLearn/pull/10495 to make sure we're not making any similar mistakes here.

**Comment by jonatanschroeder** [comment]
> I assume you've tested this and it works correctly.

I have tested it locally with a fix of names_from_user in the Python grader, and it works fine. I'll test a few other cases listed above to make sure they are covered.

> One more thing: we've implemented this incorrectly in the past, at least when it comes to things in the `grade()` function. Might be worth checking #10495 to make sure we're not making any similar mistakes here.

A cursory read of that PR seems to indicate the new PR follows a correct implementation, I'll review it again to double check.

**Pull request merged**
