### PR TITLE
Add uin to gradebook

### PR DESCRIPTION
**Pull request by RDT04**
I reverted the changes to the package-lock.json files as was asked in the comments under the project from hackillinois.

### CODE REVIEW

**Comment by nicknytko** [comment]
Continuation of #2109, created new PR because of forking issues

**Comment by mwest1066** [comment]
There still seems to be a large change to `package.json`?

**Comment by tdy** [comment]
If you're daunted by the `git revert 68edb2c` conflicts, you can manually revert `package.json` by itself:

```bash
$ git checkout Add_UIN
$ PROBLEM_COMMIT=68edb2c
$ PARENT_COMMIT=$(git log --pretty=%P -n 1 $PROBLEM_COMMIT)
$ git checkout $PARENT_COMMIT package.json
$ git add package.json
$ git commit -m 'Manually revert package.json'
```

**Comment by RDT04** [comment]
Hi,

Sorry for delay.
I have made the changes that were requested. Can someone please review them? Also, I do not need to make a pull request again for new changes. Right?

Thanks

**Comment by tdy** [comment]
You used the commands I posted? Or another way?

**Comment by RDT04** [comment]
I used copy/paste because when I went to office hours and asked Nicolas about this, he said that in this case, it would be easier. So, I did that. I think they should have the same effect though

**Comment by nicknytko** [comment]
> Hi,
> 
> Sorry for delay.
> I have made the changes that were requested. Can someone please review them? Also, I do not need to make a pull request again for new changes. Right?
> 
> Thanks

Yep, any new commits you push will show up here.

**Comment by tdy** [comment]
> I used copy/paste because when I went to office hours and asked Nicolas about this, he said that in this case, it would be easier. So, I did that. I think they should have the same effect though

Make sure you're copy/pasting from the right base commit. I'm still seeing lots of diffs here: https://github.com/PrairieLearn/PrairieLearn/pull/2153/files

**Comment by RDT04** [comment]
I just went to the prairielearn github and copied it from there. I am pretty sure that was the original version. Also, it says above here that all checks have passed. But I can check against the base commit as you said. Do you know how can I see the very 1st version without any changes made? Because I tried finding it and I was only able to see changes not the original file. 
Thanks

**Comment by tdy** [comment]
> I just went to the prairielearn github and copied it from there. I am pretty sure that was the original version.

Then it sounds like you're copying the latest `master` which is not that same revision that your PR is based on.

> Do you know how can I see the very 1st version without any changes made? Because I tried finding it and I was only able to see changes not the original file.

The only way I know of is with the `git` commands I posted above. I don't think you can get it from the UI. If you really want to view it in the UI, use the `git` commands to get the parent commit and go to `github.com/PrairieLearn/PrairieLearn/commit/#########`

```bash
$ git checkout Add_UIN
$ PROBLEM_COMMIT=68edb2c
$ PARENT_COMMIT=$(git log --pretty=%P -n 1 $PROBLEM_COMMIT)
```

**Comment by tdy** [comment]
> Also, it says above here that all checks have passed.

CI checks are just for unit tests, linting, etc.

**Comment by RDT04** [comment]
I followed the above commands to manually revert the changes, but it is not recognizing the part "--pretty=%p" and is resulting in error: unknown option `pretty=%p.' Do you know how should I resolve that? Because googling it did not help that much. Thanks

**Comment by tdy** [comment]
Here is the correct `package-lock.json`:

https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/b46f251ca7d7c5471be98395ae41be194a49bdfd/package-lock.json

**Comment by RDT04** [comment]
I think Matt said that package-lock.json that I restored was correct, but package.json had a change which is what I was trying to revert yesterday. Also, I copied package-lock.json from PL github and Matt said it was correct, so why package.json is not correct? Because I copied it from github as well.

**Comment by tdy** [comment]
I see your confusion now. When @mwest1066 wrote `package.json` above, that was a typo. He really meant `package-lock.json`.

Unfortunately now _both_ `package.json` and `package-lock.json` are out of sync. You can see the diffs here: https://github.com/PrairieLearn/PrairieLearn/pull/2153/files

Correct `package-lock.json`: https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/b46f251ca7d7c5471be98395ae41be194a49bdfd/package-lock.json

Correct `package.json`: https://raw.githubusercontent.com/PrairieLearn/PrairieLearn/b46f251ca7d7c5471be98395ae41be194a49bdfd/package.json

**Comment by RDT04** [comment]
Finally, the changes requested have been reverted. Thank you very much for helping Tim and Nicolas. I have committed and pushed the changes. Can someone please review them? Also, just out of curiosity, @tdy how did you find those correct files? Because I tried so much yesterday and was not able to find it.

**Comment by mwest1066** [comment]
Looks like the reverts removed the actual new functionality.

**Comment by RDT04** [comment]
Hi Matt,

Do you know what might have caused this? Is there anyway I can revert so it does not remove the new functionality?

Thanks

**Comment by mwest1066** [comment]
Are you participating in the Monday afternoon student dev meetings? If so, that might be a good place to work on issues with git. I don't want to try debugging your git usage via GitHub issue comments 😄

**Comment by mwest1066** [comment]
This PR has been resubmitted as #2373

**Pull request closed without merging**
