### PR TITLE
Add_uin2

### LINKED ISSUE #1304: Add UIN to Gradebook
Having the UIN in the PL gradebook would make it much easier to interface with other tools. For example, Banner grade uploads are keyed on UIN, not NetID, so this requires another level of mapping if the UIN isn't provided.

Craig had claimed that the CBTF has access to this information via AD somehow. It doesn't seem to be accessible to me...

### PR DESCRIPTION
**Pull request by RDT04**
The gradebook is in with changes reverted in package.json and package-lock.json.

Fixes #1304

### CODE REVIEW

**Comment by nicknytko** [comment]
I am still seeing changes to `package.json` and `package-lock.json`, you can undo these by running the following commands in your branch:

```bash
git checkout master -- package.json
git checkout matser -- package-lock.json
```

This will revert those files to the copies found in master.

**Comment by nicknytko** [comment]
yay that worked 🎉

**Comment by nicknytko** [comment]
Resolves #1304

**Comment by mwest1066** [comment]
Could we make a similar change to https://github.com/PrairieLearn/PrairieLearn/tree/master/pages/instructorAssessmentDownloads

All the CSV files here should include UIN, except for the `*ByUsername*` files.

**Comment by RDT04** [comment]
Yes, I can try doing that.

**Comment by nwalters512** [comment]
@RDT04 we're looking at changing the way PrairieLearn is licensed - what's the best email to reach you at?

**Comment by RDT04** [comment]
Sorry, I am not associated with PL Dev anymore, but you can reach me at Rushilthakkar04@gmail.com

**Pull request merged**
