### PR TITLE
Multiple True/False

### PR DESCRIPTION
**Pull request by tnip**
See #200.

Documentation needs to be updated.

### CODE REVIEW

**Comment by mwest1066** [comment]
Thanks Terence! I'm in a proposal-writing crunch until Wednesday, but I'll review and merge this as soon as possible after that. Does your comment about docs mean that you will update the docs in this pull request?

**Comment by tnip** [comment]
I can either do it in this PR or in a separate PR, your call.

**Comment by tnip** [comment]
Also: I overrode the `gradeAnswers` method here, which might have to be fixed later when #197 happens.

**Comment by tnip** [comment]
For the purposes of getting this PR in with "minimal" cruft, I've removed the grading stuff from the schema. I've left it in the server for now with "sane" default options.

**Pull request merged**
