### PR TITLE
Declare questions.qid and assessments.tid to be NOT NULL

### PR DESCRIPTION
**Pull request by nwalters512**
I verified that these columns are in practice null in production environments.

### CODE REVIEW

**Review by mwest1066 — APPROVED** [review]
Woohoo! 🎉

**Comment by nwalters512** [comment]
Dang, this is blocking this change:

https://github.com/PrairieLearn/PrairieLearn/blob/c1125a06181247fe9abf50248a69819683fb585d/apps/prairielearn/src/sprocs/sync_assessments.sql#L387-L399

@SethPoulsen is there something else we could do here? Perhaps insert the full sharing QID (`@sharing-name/qid`) instead of `NULL`? I haven't fully thought through the implications of that.

**Comment by nwalters512** [comment]
Seth, if you have the bandwidth, I'd definitely appreciate it if you could look into this! I think the best course of action would be to open and merge a separate PR that would stop writing `NULL` to `questions.qid`, which should then make this PR very easy to land.

**Comment by nwalters512** [comment]
@SethPoulsen bump, any chance you can take a look at this?

**Comment by SethPoulsen** [comment]
You and I had a look at it a while ago. Our conclusions were that:
- its not totally clear why shared questions don't show up in assessments in local dev
- in order to handle the case of local dev with missing shared quesitons properly, we probably need to add a new column to the `questions` table which denotes if a given row in the table is a 'fake' row or not--this column would only ever be used in local dev

How high priority is this for you? I haven't been working on it because I have instead been focusing on the tasks to get question sharing out of Beta. This was not as high priority for me because it only affects error messaging for local dev in question sharing.

**Comment by nwalters512** [comment]
@SethPoulsen thanks for the reminder/summary. This isn't _super_ high priority, but not having to worry about `NULL` values in more places would be a nice quality-of-life improvement. I'm fine to keep this on the backburner until some of the more important question sharing features are done.

**Comment by nwalters512** [comment]
I don't see us making traction on this anytime soon.

**Comment by SethPoulsen** [comment]
you could put an issue for this on the Question sharing project page if you want since it's being blocked by that.

**Comment by mwest1066** [comment]
> you could put an issue for this on the Question sharing project page if you want since it's being blocked by that.

Done, see #10269

**Pull request closed without merging**
