### PR TITLE
Start out pl-order-blocks in alphabetical order.

### LINKED ISSUE #4920: Start out pl-order-blocks in alphabetical order
Add an option to alphabetized lines in shuffle-options (motivated by https://dl.acm.org/doi/pdf/10.1145/3017680.3017704). It makes the lines more easily findable for students but likely doesn't give anything away compared to pure shuffling.

Originally suggested by @nathanielweinman in https://github.com/PrairieLearn/PrairieLearn/issues/3476

### PR DESCRIPTION
**Pull request by roloza7**
Adds the `source-blocks-order='alphabetized'` option to `pl-order-blocks`. 

Also adds a new test in the relevant question for the test course. Hopefully resolves #4920!

### CODE REVIEW

**Comment by roloza7** [comment]
I have reviewed and hereby sign the CLA

**Review by nwalters512 — COMMENTED** [review]
This looks good! Please document this new option in the [element docs](https://github.com/PrairieLearn/PrairieLearn/blob/d240fcf137acb56464fe29d1fcb11949ed0e7dc7/docs/elements.md). It's probably worth calling out that this specifically uses the HTML to perform alphabetization, which may produce unexpected results if the contents aren't just a simple string.

Could you also add a new example of this to either `testCourse` or `exampleCourse`?

**Comment by SethPoulsen** [comment]
I second everything @nwalters512 says. This element is frequently used in such a way that the first HTML character is not the first visible character, for example when its used with LaTeX at the beginning, or code formatting, etc., so if sorting will be done that way, it should be documented. Thanks for your contribution @roloza7!

**Comment by nwalters512** [comment]
@roloza7 many thanks for the contribution! As this branch was created on your fork, it's difficult for me to take over your branch and make the necessary changes. I'm going to create a new PR and add documentation and examples so we can get this merged; I'll link back here for credit.

**Comment by nwalters512** [comment]
Superseded by #6959.

**Pull request closed without merging**
