### PR TITLE
Submissions artifact pdf upload

### PR DESCRIPTION
**Pull request by andrewstec**
This PR Introduces New Features: 

- Page view (`instructorScrapPaper`) that generates a PDF with a unique barcode on each page. The PDF is printed and each sheet is handed out to students as scrap paper. The scrap paper is collected and scanned to produce a PDF of used barcoded scrap paper.
- Page view (`instructorScanPaper.ejs`) that takes used barcoded scrap paper PDF and decodes the barcode on each page. The page is uploaded to S3 and associated with the barcode.
- Element (`pl-barcode-scan`) that allows a student to submit the barcode on the scrap paper they wrote on AND view the scrap paper they wrote on once the barcode has been decoded in the `instructorScanPaper.ejs` view.

This continues to be a draft, as this PR should not necessarily be merged. 

Two additional PRs have been produced that segment the logic of this PR to be read easily. 

1) https://github.com/PrairieLearn/PrairieLearn/pull/5190
2) https://github.com/PrairieLearn/PrairieLearn/pull/5192
    
PR 1 can be reviewed
then PR2 can be reviewed. 

PR2 can be merged into PR1, and then PR1 can be merged into master.

### CODE REVIEW

**Comment by andrewstec** [comment]
@mwest1066 Here is a draft for the time-being. If we want to put this under a project area, we can (probably in the manual grading area).

I would like to get the core functionality working for Thursday. That would look like an end-to-end test for the entire process.

Some further refinement and discussion will be needed. ie. Potentially switching out Quagga/Quagga2 (Quagga2 is supported but broken in Node JS and Quagga is not supported but works in Node JS, etc.), and a more robust algorithm to support decoding PDF documents that have terrible resolution, upside-down pages, etc.

**Comment by nwalters512** [comment]
@andrewstec would you like us to start reviewing now, or should we wait for you to take it out of draft status?

**Comment by andrewstec** [comment]
> @andrewstec would you like us to start reviewing now, or should we wait for you to take it out of draft status?

Please wait until I take it out of draft status. I was just writing tests and found an optimization issue with the barcode scanner. There is still more work to do, but I got blocked by this today. 

I will check-in on Thursday evening. It could be ready then.

**Comment by andrewstec** [comment]
> > @andrewstec would you like us to start reviewing now, or should we wait for you to take it out of draft status?
> 
> Please wait until I take it out of draft status. I was just writing tests and found an optimization issue with the barcode scanner. There is still more work to do, but I got blocked by this today.
> 
> I will check-in on Thursday evening. It could be ready then.

It is almost there, but it will be a bit longer. If you want, you can take a look at the tests file to see what was done. I am just uploading it to S3 and loading the PDF in the view. 

However, code quality could be upped. I will be in touch on Monday. @nwalters512 I would probably hold off until reviewing longer.

**Comment by andrewstec** [comment]
@mwest1066 @nwalters512 

This PR draft references two actual PRs. I would imagine that reviewing the segmented PRs is easier, but the same code is found, in full, in this PR. I can close this, take it out of draft status, or whatever you prefer.

**Comment by andrewstec** [comment]
Walk through the entire flow to understand this PR:

I would recommend switching to this branch and loading the pl/scrap_maker and /pl/scan_paper routes. 

Once you produce a PDF file with pl/scrap_maker, enter one of the barcodes onto the `12. Barcode submission` found in the `HW1 | Homework for automatic test suite` of the QA Test Course.

No PDF data will be displayed on the question until you upload the PDF file to the /pl/scan_paper route.

**Pull request closed without merging**
