### PR TITLE
Fix grading for multiple T/F

### PR DESCRIPTION
**Pull request by tnip**
Never noticed in testing, but the grading's a bit wonky as-is. This PR fixes it.

### CODE REVIEW

**Comment by mwest1066** [comment]
Would you mind rebasing this onto master? Thanks!

**Comment by mwest1066** [comment]
Are you up to date with current master? I merged feature-multiTrueFalse some time ago, and there have been more commits since then. My current master is at 1045e53249a1a615948ec31473edda76bd9f3ce9. Is this also what you see?

I think it's just the last three commits in this sequence that we need, but it would be good if they were based off of 1045e53249a1a615948ec31473edda76bd9f3ce9.

**Comment by mwest1066** [comment]
Sorry to keep being such a pest with this, but this is still not correctly rebased onto master. Instead you've done some more merges and now we've got several copies of the history in parallel.

To see the history in git I use the "git la" alias defined in the "Git configuration" section of http://lagrange.mechse.illinois.edu/git_quick_ref/

One sure way of producing the correct tree is as follows:

* checkout master
* checkout a new branch called MTF2 or something starting from master
* do "git cherry-pick" to move across just the three commits you want (the ones listed right at the top above)
* do "git al" to check that the MTF2 branch starts from master (1045e53249a1a615948ec31473edda76bd9f3ce9) and contains just the three commits you want
* issue a new PR for the MTF2 branch and delete this PR

**Comment by tnip** [comment]
That was stupid of me; this is why I shouldn't do things when I'm tired. Literally realized I should've branched & cherrypicked while I was lying in bed. Sigh. Coming soon.

**Comment by tnip** [comment]
See #243.

**Pull request closed without merging**
