### PR TITLE
Update python-requirements.txt

### PR DESCRIPTION
**Pull request by gminnocenti**
add library moviepy 2.1.1 .

### CODE REVIEW

**Comment by gminnocenti** [comment]
I have reviewed and hereby sign the CLA

**Comment by eliotwrobson** [comment]
Recheck

**Comment by gminnocenti** [comment]
recheck

**Comment by jonatanschroeder** [comment]
Hi, @gminnocenti , thank you for your contribution. Before we consider this update, can you clarify:

* What do you need this dependency for?
* Are you planning to use this in your server.py for question generation/parsing/internal grading? Note that if you are planning to use it for the external grader or a workspace, there is a different process to follow.
* Have you tried [installing this dependency in your own course](https://prairielearn.readthedocs.io/en/latest/questionRuntime/#installing-libraries-in-your-course) instead? This is usually recommended for libraries that are specific to a particular course and that will not be used often by other courses.
* If you still believe that this is useful in general and expected to be used in server.py (directly or indirectly), can you please follow [the instructions here](https://prairielearn.readthedocs.io/en/latest/questionRuntime/#add-the-library-to-python-requirementstxt)? In particular, make sure that the file remains in alphabetical order, and that your commit message (and PR title) are descriptive.

**Comment by nwalters512** [comment]
I'd strongly recommend against trying to do any video manipulation in `server.py`, whether through a dependency installed in PL itself or via one installed in your course. That's likely to be hugely CPU-intensive and will encounter issues with timeouts and data sizes. As Jonatan said, it'd be helpful to hear more about what you want to do, but in the meantime, I'd advise against trying to use this library in `server.py`.

**Comment by echuber2** [comment]
It looks like the course staff's intended usage is described here: https://github.com/ace-lab/pl-ucb-star-assessments/blob/53af1a0aa83dff9435721cc36470a4e282b02474/elements/pl-graph-animate/README.md

I'd also recommend against doing that on the server. If the question isn't dynamically generated, you could generate an animation ahead of time (working locally) and commit it to the questions repo. Or, there may be another libary that could produce a client-side dynamic animation for the browser to render.

**Comment by gminnocenti** [comment]
Good afternoon, 
Thank you  for taking the time of reviewing my contribution. The reason why I made this contribution is because, I developed an element for my course called pl-graph-animate. That can be seen in the previous comment. For this element I used the dependency moviepy to create animation's (videos)  of graph related questions (bfs,dfs). While developing the element I installed the dependency locally on my course as detailed in the PrairieLearn documentation, but I decided to contribute to the main repository in case other contributor's wish to create  elements that render video. Thank you once again for your feedback and consideration!

**Comment by nwalters512** [comment]
While what you've done is quite clever, I really think this use case is really not something we want to encourage. Can you share more about the performance characteristics of this element? How large (in KB/MB/characters/whatever) are the base64-encoded strings that it produces? How long does the element take to render?

**Comment by gminnocenti** [comment]
Thank you for your feedback and comments! For a 10 second video the base64-encoded strings has 87404 characters (65553 bytes), but on average most  base64-encoded strings are comprised of around 100,000 characters.  In terms of how long the element takes to render I would say around 10 seconds depending on the duration of the video. Also your concerns about issues with timeouts are true when the video's duration increases.

**Comment by nwalters512** [comment]
Gotcha. While that's thankfully not a crazy amount of data, the duration and the amount of CPU that must be used in rendering this video definitely concerns me.

I'd echo Eric's suggestions:

- If the data being animated is static, you can pre-render it and then just serve the video file (which should be very small, based on the size of the base64-encoded string you shared.
- If the data being animated is dynamic, I'd recommend finding a way to do the rendering on the client.

I'm going to close this PR, but I'm happy to continue brainstorming ways to make your element lighter on our infrastructure, either here or in a [GitHub discussion](https://github.com/PrairieLearn/PrairieLearn/discussions).

**Pull request closed without merging**
