### PR TITLE
install MathJax with npm; don't include in git

### PR DESCRIPTION
**Pull request by mwest1066**

### CODE REVIEW

**Comment by nwalters512** [comment]
So, since GitHub won't show me the entire diff, what were the two additions? I see one is adding mathjax to `package.json`, what's the other?

**Comment by mwest1066** [comment]
```text
mwest@sage:PrairieLearn$ git diff master..mathjax-npm package.json server.js
diff --git a/package.json b/package.json
index 4b075743..b1c6a66a 100644
--- a/package.json
+++ b/package.json
@@ -26,6 +26,7 @@
         "javascript-natural-sort": "0.7.x",
         "jju": "1.3.x",
         "lodash": "4.17.x",
+        "mathjax": "2.7.x",
         "mersenne": "0.0.x",
         "mongodb": "2.2.x",
         "numeric": "1.2.x",
diff --git a/server.js b/server.js
index f0c56069..a49a4ac1 100644
--- a/server.js
+++ b/server.js
@@ -49,6 +49,7 @@ app.use(bodyParser.urlencoded({extended: false}));
 app.use(cookieParser());
 app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
 app.use(express.static(path.join(__dirname, 'public')));
+app.use('/MathJax', express.static(path.join(__dirname, 'node_modules', 'mathjax')));

 // Middleware for all requests
 // response_id is logged on request, response, and error to link them together
```

**Comment by nwalters512** [comment]
Lgtm! Would have done a diff myself but am away from my machine for the day :)

**Comment by mwest1066** [comment]
Extra thanks for the remote review in that case!

**Pull request merged**
