### PR TITLE
Add mkdocstrings

### LINKED ISSUE #11006: Move from Sphinx to mkdocstrings
Sphinx currently is just another build step in our documentation, which adds complexity and sources for issues integrating two very different documentation sources together. Moving to [mkdocstrings](https://github.com/mkdocstrings/mkdocstrings) allows for an integrated documentation experience, and we could even start documenting existing Python elements with this. 

A concrete advantage of moving to mkdocstrings would be that we can unify the documentation for Python elements to be colocated alongside the elements themselves, so there is less concerns about it staying up to date.

### PR DESCRIPTION
**Pull request by reteps**
This PR moves from Sphinx to mkdocstrings for code autodocumentation

Resolves #11006

Requires #11051 

https://prairielearn--11048.org.readthedocs.build/en/11048/python-grader/reference-docs/

### CODE REVIEW

**Review by eliotwrobson — COMMENTED** [review]
Haven't looked super closely yet, but from a glance I think mkdocstrings is the way to go for the autograder documentation 👍🏽 splitting the elements docs pages makes things much more manageable.

**Comment by reteps** [comment]
Mkdocstrings only works with canonical imports, so I had made all those `__init__.py` files.

However, this doesn't seem like it works alongside our current folder structure.

To autodocument prairielearn python code, we would need to change the folder structure to:

```
python/
--- prairielearn/
------ <files.py>
------ elements/
---------- my_element.py
```

**Comment by jonatanschroeder** [comment]
> Partially resolves #1843

Note that GitHub will ignore the "partially" and will close the issue when this PR is merged. You can say something like "partially handles" or "partially addresses", but I'd avoid resolves/fixes/closes.

**Comment by SethPoulsen** [comment]
Is there a reason this isn't two separate PRs: one for changing to mkdocstrings, and one for rearranging docs?

**Comment by reteps** [comment]
> Is there a reason this isn't two separate PRs: one for changing to mkdocstrings, and one for rearranging docs?

I will split this up into two PRs to make it easier to review.

**Comment by reteps** [comment]
Closing in favor of a cleaner PR targeting the correct branch.

**Pull request closed without merging**
