### PR TITLE
Use google-auth-library instead of googleapis

### PR DESCRIPTION
**Pull request by nwalters512**
`googleapis` is a massive package, weighing in at ~120MB and taking ~250ms to load on my machine. `google-auth-library` is comparably much smaller: it's only 680kB and takes ~20ms to load on my machine.

This change should decrease the size of our Docker image, decrease application boot time, and make our production AMI builds complete more quickly.

### CODE REVIEW

**Comment by trombonekenny** [comment]
OK that's really weird because I was running into type checking problems with the `authCallbackOAuth2.js` file and was looking at `googleapis` vs something else that type checked better.... at the same time you were writing this PR.

**Comment by trombonekenny** [comment]
> OK that's really weird because I was running into type checking problems with the `authCallbackOAuth2.js` file and was looking at `googleapis` vs something else that type checked better.... at the same time you were writing this PR.

I'll leave that file alone right now and wait for a merge. :)

**Review by mwest1066 — APPROVED** [review]
Awesome! Hopefully this will also cut down on the number of versions bumps we get from dependabot for `googleapis`.

**Comment by trombonekenny** [comment]
How do you test these things? Throw them up on a staging server?

**Comment by mwest1066** [comment]
> How do you test these things? Throw them up on a staging server?

Yep!

**Pull request merged**
