### PR TITLE
Draft: Canvas2PL for new quizzes API

### PR DESCRIPTION
**Pull request by nishanthkarthik**
This tool imports questions from Canvas new quizzes to PL. Images hosted in third party buckets are vendored into clientFilesQuestion.

New quizzes in Canvas: [API](https://canvas.instructure.com/doc/api/new_quiz_items.html), [Comparison](https://docs.google.com/document/d/11nSS2EP0UpSM6dcuEFnoF-hC6lyqWbE9JSHELNmfG2A)

Caveats:

- Unimplemented question types: We will update this as we test with a larger corpus of questions internally
- Swagger generated code: The swagger used by canvas is not actually fully swagger 1.2 compliant. I processed the swagger jsons by hand before invoking the codegen because the codegen breaks otherwise. I also modified the generated `api_client.py` to handle the non-existent "sum types" in swagger 1.2. I need to figure out a workaround instead of committing generated code
- The image names are UUIDs. This may be improved with more API calls. I don't know yet.
- The console output may not be super informative. Your feedback is appreciated!
- The `CanvasConfig` needs to be parsed from CLI args. It's hardcoded in the source currently

Steps:
- Add tools/question_converters/lib to a pth file in your python venv
- Modify the `CanvasConfig` configuration in `main.py`
- Run `main.py`

FYI @trombonekenny @firasm

### CODE REVIEW

**Comment by trombonekenny** [comment]
I'd encourage you to weigh whether the exports of quizzes already in the Canvas UX could be used as a data source, or if an API/authenticated call is needed. In my experience, it's easier if you don't have to steward someone else through the API authentication process (and more repeatable for testing based on static content). 

I'm not sure what that currently looks like with Canvas, but though I'd throw that out there. It's fun to see work in this space - people will definitely appreciate building PL content from Canvas question pools!

**Comment by nishanthkarthik** [comment]
@nwalters512 Of course! I made the draft PR for users to try out on their canvas quizzes and find bugs. I'll clean up the PR before I mark it ready for review

@trombonekenny I followed the structure of previous canvas2pl which as I understand it requires auth tokens. I have not really looked at canvas exports.

**Comment by firasm** [comment]
Thanks for the PR, and the early feedback. 

@nishanthkarthik perhaps I was wrong for suggesting this should live in the PL repo. Maybe we should host/store this in a separate repo instead?

It's only peripherally related to the PL code base so moving it out makes some sense. 

Also, we want to be careful with how much dev hours we want to put into refactoring it so it's suitable for inclusion here. 

Let's talk about this next time we meet!

**Comment by nwalters512** [comment]
@firasm @nishanthkarthik can you share the result of your discussion? I'd like to keep the PL PR list clean, so if you plan to refine this elsewhere before submitting it for inclusion in PL, I'd like to close this until that time.

**Comment by nishanthkarthik** [comment]
Sure, let's close this one! Thanks for the reminder :)

**Pull request closed without merging**
