### PR TITLE
Add RFC for full gradebook

### PR DESCRIPTION
**Pull request by Kieran-Weaver**

### CODE REVIEW

**Comment by Kieran-Weaver** [comment]
I have reviewed and hereby sign the CLA

**Comment by Kieran-Weaver** [comment]
recheck

**Comment by nwalters512** [comment]
@Kieran-Weaver do you still have interest in taking this out of draft and working through review and implementation?

**Comment by Kieran-Weaver** [comment]
Hi, no, I'm no longer able to. Sorry for leaving this to get stale.

**Comment by nwalters512** [comment]
Thanks for letting us know!

**Pull request closed without merging**
