### PR TITLE
Change MathJax fontCache from global to local

### PR DESCRIPTION
**Pull request by echuber2**
Maybe closes https://github.com/PrairieLearn/PrairieLearn/issues/6495 (untested on Windows yet -- could be barking up the wrong tree)

This changes the `fontCache` setting for MathJax to `local`, which should create one or several cache(s) within each SVG object instead of one per page.

For background: I'm wondering if the issues @trombonekenny describes in https://github.com/PrairieLearn/PrairieLearn/issues/6495 might be due to the other recent changes to MathJax handling (https://github.com/PrairieLearn/PrairieLearn/pull/6358, https://github.com/PrairieLearn/PrairieLearn/pull/6442) which load MathJax asynchronously, combined with the fact that we have MathJax set to use the _global_ font cache injected on the page. ([See the MathJax developer explanation at the comment linked here.](https://github.com/mathjax/MathJax/issues/2897#issuecomment-1180218087))

On a related note, I see we have this code that tries to manually copy the globally cached parts for `pl-drawing`:

https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-drawing/mechanicsObjects.js#L887

Keeping in mind other weirdness that font rendering has exhibited in `pl-drawing`, and in light of what the code linked in `mechanicsObjects.js` does, maybe we should just set `fontCache` to `'none'` instead, which I think does the same thing natively, inlining each shape. ([MathJax doc reference](https://docs.mathjax.org/en/latest/options/output/svg.html#option-descriptions); see also the MathJax developer's explanation linked above.)

### CODE REVIEW

**Comment by nwalters512** [comment]
I can confirm that this fixes things for me on macOS Chrome!

Have you or @trombonekenny made any effort to reproduce this in isolation? This very much feels like a bug to me; regardless of how we have the font cache configured, I'd expect switching the rendering method to still work. It'd be great if one of you could get an isolated reproduction and submit an issue to the MathJax folks.

> maybe we should just set fontCache to 'none' instead, which I think does the same thing natively, inlining each shape

I think this is reasonable as long as we continue rendering things only on the client; I don't think we need to worry about the complexity or number of DOM nodes that MathJax creates. And at any rate, if we move to rendering on the server, we'd probably not use MathJax anyways.

**Comment by nwalters512** [comment]
> What do you mean by isolation?

As in, in an HTML document outside of PrairieLearn. See the MathJax bug report template: https://github.com/mathjax/MathJax/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by echuber2** [comment]
I'm trying to put that together. I think indeed there may be some bugs in how MathJax handles multiple loaders and the global cache option. But for our case the fastest thing to do may be to just use `none`.

**Comment by nwalters512** [comment]
Relevant: https://github.com/PrairieLearn/PrairieLearn/issues/6495#issuecomment-1286303715

**Comment by echuber2** [comment]
Superseded by https://github.com/PrairieLearn/PrairieLearn/pull/7280 and/or https://github.com/PrairieLearn/PrairieLearn/pull/6974

**Pull request closed without merging**
