### PR TITLE
Add local cache for workspace urlRewrite query

### PR DESCRIPTION
**Pull request by tdy**
Caches `questions.workspace_url_rewrite` to address DB load issues.

### CODE REVIEW

**Comment by nicknytko** [comment]
Do we ever want to dump this cache? I don’t expect this value to change very often (if at all), but maybe we can flush on course sync just to be safe?

**Comment by mwest1066** [comment]
> Do we ever want to dump this cache? I don’t expect this value to change very often (if at all), but maybe we can flush ~on course sync~ after some interval just to be safe?

I pushed an update to age out old cached values. I actually don't think it's needed in this case because we aren't going to have more than a million workspaces or something, but it's good hygiene to avoid slowly growing memory without limits 😄 

@tdy does the update look ok to you?

**Comment by tdy** [comment]
> @tdy does the update look ok to you?

Yep looks good! I just wasn't sure what happened with the CI.

**Comment by mwest1066** [comment]
> Yep looks good (and tested locally)! I just wasn't sure what happened with the CI.

I fixed the CI now (need to clear the setIntervals).

**Pull request merged**
