### PR TITLE
Course questions

### LINKED ISSUE #912: Add Questions to Course view
Let people who can view the Course page also see the Questions tab (currently just linked under course instances)

Confirm that viewer level access can see those too.

(Also add a section to Courses that list course instances without having to go back to the main page)

### LINKED ISSUE #988: Compare question use across semesters at course level
Create a "Questions" page for the course view which:

- [x] Lists of all course questions (equivalent to the one available for a course instance)
- [x] Create "courseQuestion" view (like instructorQuestion) and enable the hyperlinks from each question title.
- [x] Displays a column for each course_instance, with the assessment(s) using that question listed underneath (equivalent to the rightmost column of the Questions view in a course instance)
- [ ] (Extra) Allow individual course instances to be toggled on/off in this view, so specific course instances can be compared (for comparisons like, e.g., "last two years" or "semesters I taught the class")
- [x] (Extra) Create "courseIssues" view and enable links on the course navbar and from Questions/Question view.
The first two checkpoints are identical to #912

### LINKED ISSUE #1019: "Issues" badge on instructorQuestion page should pre-filter by qid
Clicking on the badge on instructorQuestions (i.e., the question list) takes us to instructorIssues with a qid filter already applied (to show issues with that question), but doing so on instructorQuestion (i.e., individual question view) does not apply this filter.

### PR DESCRIPTION
**Pull request by rbessick5**
Currently, this addresses the first checkpoint of #988 . There are no links to individual questions yet (I need to do the right thing with variants/submisisons that don't belong to a course_instance before this can be added).

Closes #988 , closes #912 , and fixes #1019

### CODE REVIEW

**Comment by rbessick5** [comment]
FYI, commit 573e9fc includes amending the 'Issues' badge on courseQuestion so it links to issues affecting that question instead of all issues (to match the behavior of such badges on courseQuestions). This change should probably also happen to instructorQuestion.

**Comment by rbessick5** [comment]
At this point, this PR now satisfies the first two checkpoints of #988 (as well as an extra one); I'll add the course_instance assessment column next.

Am I mis-reading the Travis CI log that this passed all checks, but still failed?

**Comment by nwalters512** [comment]
```
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sh ./tools/verify-changelog.sh; fi" exited with 1.
```

We require all PRs to have a corresponding entry in `ChangeLog.md`, and Travis checks for this automatically and fails if it's missing 🙂

**Comment by nwalters512** [comment]
The amount of code duplication between `instructorIssues/*` and the new `courseIssues/*` is extremely worrying to me. We should factor out the shared bits (almost everything?) and DRY things up a bit.

**Comment by rbessick5** [comment]
Function-wise, the only difference between the two (as well as `courseQuestion` vs `instructorQuestion` and `courseQuestions` vs `instructorQuestions`) is that the instructor versions are restricted to a single course_instance. There's probably a good way to combine all of this into a single set of pages that checks what situation you're in.

**Comment by rbessick5** [comment]
I was too hasty when I removed the course_instance LEFT JOIN from courseIssues.sql; once I add that back in, we can make courseIssues and instructorIssues 100% identical. I can just change the server.js routing to point both to the same copy.

Given this, would we prefer to have the shared page live under `courseIssues/*` or `instructorIssues/*` (or a third name)?

**Comment by rbessick5** [comment]
This changes `courseQuestion.*` such that it could fully replace `instructorQuestion.*`

I'm thinking the right thing to do here would be to make these all `course*` pages, since questions belong to courses. What the correct behavior would be for the question list could be either 1) instructorQuestions should list assessments for the current semester only (current behavior) while courseQuestions list everything, or 2) make these pages identical as well, so comparisons across semesters can happen within a course instance (this is already happening in the question statistics on instructorQuestion).

**Comment by mwest1066** [comment]
I think it would be less confusing to users to have the pages be identical, so that if you are on the Questions page it always looks the same irrespective of how you got to it.

However, I'm a bit worried that the all-semesters version is going to be too crowded or confusing for regular use. I'd like to see what this looks like before making a decisions.

**Comment by rbessick5** [comment]
@mwest1066 You can see the table with all course_instances listed in the latest commit. Right now, the sort function on these columns is free-text entry. The SQL to get arrays of all_assessments objects (mirroring all_tags and all_topics) shouldn't be too hard, but I'm unsure of exactly how to write tablesorter() to have a non-static set of columns.

With many course_instances (e.g., pl-tam212) this table is a bit messy; I particularly don't like that the scroll bar might be hidden at the bottom of the (long) question list, such that you might not realize it exists.

It would be cool to be able to toggle individual columns of this table into/out of view (in which case, I'd suggest course-space version default all visible, and the course_instance-space version default only the current course_instance visible), but I don't know if we can/want to dynamically re-render this panel in response to, say, an array of check-boxes.

**Comment by rbessick5** [comment]
This commit borrows a partial from instructorQuestions to make the assessment badges, so they all have (broken) links to assessments in this commit. Potential choices for what to do here (that I can think of) include:
1) Remove any links from these badges.
2) Create a "courseAssessment" view that can pick an assessment from a specific course_instance and render it in course-page space (like what we did with the courseIssue page; this might lead to another redundancy with instructorAssessment)
3) Create links into the corresponding course_instance instructorAssessment page for every badge; users with incorrect permissions hit errors if they follow.
4) Determine user permissions assessment-by-assessment (course_instance-by-course_instance?) and create links to instructorAssessment for exactly the assessments the user has permission to view with no links on the other badges (probably the slowest/most intricate answer).

**Comment by rbessick5** [comment]
This branch probably needs a rebase before I make any more significant changes, so I'll do that next.

**Comment by rbessick5** [comment]
@mwest1066 I've rolled back the (incomplete) column selection commit, so this should be ready for you to take a close look at. 

This does still need a ChangeLog entry.

**Comment by mwest1066** [comment]
CI is failing -- maybe need a ChangeLog entry?

**Comment by rbessick5** [comment]
Yes -- from my reading of the CI report that's the only check that is failing. I'll make a change and push it now. I'll look to copy the format of the previous entries, but feel free to edit as needed.

**Comment by rbessick5** [comment]
I ran a rebase right before committing the ChangeLog entry (to get the newest version of the file) and it broke something in the question auto-testing; I'll need to chase that down now.

**Comment by rbessick5** [comment]
It looks like what is breaking this is the recently-merged `course-instance-for-all-variants` branch -- compare `courseQuestion.js` at line 114 with `instructorQuestion.js` line 110 in their calls to `question.startTestQuestion()`

Right now `courseQuestions` is being used both inside and outside a `course_instance`; I can revert this to fix the question testing, and remove the Test Once / Test 100 times buttons from the courseQuestion view (since they don't have a course instance to pass on). Does this mean that `courseQuestion` is generating variants without a valid `course_instance` and/or is that a problem?

**Comment by rbessick5** [comment]
Relatedly, this branch is using `courseIssues` both inside and outside a `course_instance`, so the `instructorIssues` pages are unused and could probably be deleted.

**Comment by rbessick5** [comment]
@mwest1066 This now passes the checks for testing (within a course_instance) and simply hides the testing buttons when no course_instance is defined. I think this still breaks some real-time feedback for a submission to an external grader by an instructor at course-level.

The resulting fix also means that `pages/instructorIssues/*` and `pages/instructorQuestion/*` are no longer used at any point, so I'll make one more commit that deletes them.

**Comment by rbessick5** [comment]
@mwest1066 This branch is rebased and ready to go.

Closes #988 , closes #912 , and fixes #1019

**Comment by rbessick5** [comment]
@mwest1066 Giving this a poke (and a rebase) to see where you stand on getting it merged?

**Comment by mwest1066** [comment]
I'm on a big push to get code merged at the moment, so I'll try and get this one in as well. Thanks for poking me!

**Comment by mwest1066** [comment]
Superseded by #1503

**Pull request closed without merging**
