### PR TITLE
Documentation fix

### PR DESCRIPTION
**Pull request by johnnyoshika**
Some documentation fixes that I'd like to suggest.

### Summary:

*  Replace reference to `pages/instructorQuestion` with `pages/instructorQuestionPreview` here: https://prairielearn.readthedocs.io/en/latest/dev-guide/, as `pages/instructorQuestionPreview` superseded the former page here: https://github.com/PrairieLearn/PrairieLearn/commit/0019d997bf0d7e42588faa94130da23e4d84f888#diff-9672e40fe7e2b2b203956bdc79c5e450eb09be38c268458f5e17902fe8b0e581
* Add source directory options for PowerShell and WSL to accompany WIN CMD and macOS/Linux: https://prairielearn.readthedocs.io/en/latest/installingLocal/
* Suggest `--rm` when installing node packages inside a container as there's no need for the container to persist: https://prairielearn.readthedocs.io/en/latest/installingLocal/
* Change path to Python's `requirements.txt`, as the one that's currently referenced doesn't exist: https://prairielearn.readthedocs.io/en/latest/installingNative/
* Fix 'my' -> 'may' typo: https://prairielearn.readthedocs.io/en/latest/faq/

### CODE REVIEW

**Comment by mwest1066** [comment]
Thanks for the fixes!

**Comment by cheeren** [comment]
@johnnyoshika are you interested in being part of the PL user community in vancouver? (i'm a detective :) )

**Comment by johnnyoshika** [comment]
@cheeren Yes, I'd like to join. How do I do that?

BTW, I went to the engineering school where you teach. I'm also a detective. 🙂

**Comment by cheeren** [comment]
Drop me a note at cheeren@cs.ubc.ca and I'll invite you to the relevant slack channels!

**Comment by johnnyoshika** [comment]
@cheeren Thanks for the invites! I just joined.

**Pull request merged**
