### PR TITLE
Change File Upload/Download to use base64 encoding, and filter out files from questions/

### PR DESCRIPTION
**Pull request by mvd7793**
I fixed the .zip bug by switching to base64 encoding. Files are read as base64, served from data URLs that way, and are now inserted into the database with base64 encoding (along with the data URL prefix so scripts can programmatically determine their file type if it is not already known).

Sample screenshot of a database entry for a file with this PR:

I also fixed a bug that would cause an error if a random file (e.g. `.DS_Store`) appeared in questions/ by filtering out only directories.

@mwest1066: Two things! 
1) The only actual change to server.js should be the `async.filter` call, but since it's async it messed with all the tabbing which causes GitHub's diff to appear larger than necessary.
2) I have tested this diff in both Firefox and Chrome and I'm confident it works, but would appreciate a second test on a different computer if you don't mind to ensure we don't find any surprises like last time.

@zillesc The only change on your end is that in the database, files are stored with base64 encoding. The grading script will need to decode it before grading. (With the first PR, all you got was raw file text. Ideally you know what kind of file the student is uploading and the raw base64 encoding should work, but just in case I've included the data URL prefix generated by the browser when it was read. Should help if, for example, someone accidentally uploads their source code instead of a ZIP file.)

### CODE REVIEW

**Comment by mvd7793** [comment]
cc @smeenai

**Comment by mwest1066** [comment]
Awesome, thanks, I’ll test and pull tomorrow night (with any luck).



On Mar 4, 2015, at 15:22, Matthew Dierker <notifications@github.com<mailto:notifications@github.com>> wrote:


cc @smeenai<https://github.com/smeenai>

**Comment by mwest1066** [comment]
Testing now on Safari. If I click on the link directly then I get a new tab with the binary file contents displayed. If I do right-click and "Download Linked File" then it doesn't handle the filename correctly and just saves it as "Unknown", which is the binary zip file but without a ".zip" extension. I checked Firefox and Chrome and they both worked fine, as you said.

File uploading worked fine. I tested Safari and verified that extracting data from mongo and un-base64ing it resulted in the exact original binary file.

One thing:

Can you rebase this branch onto current master? At the moment this is based on b0684e80e664c87fa992014df4ddd19224701801 rather than the latest master a86eacf081667e894e1918781a8b730941f12a77 which is the merge.

**Comment by mvd7793** [comment]
I think that should do it with the master fix! Sorry, I hadn't configured upstream correctly.

re: Safari, that's [unfortunately expected](http://caniuse.com/#feat=download) because of lack of HTML5 support for the `download` attribute. IE would be the same.

From what I've learned: The older "right" way to force a file download is to specify a Content header server-side, but that seems challenging to implement in PrairieLearn since the model is all question information is sent to be rendered client side. Using an external server would require a firewall change -- probably not worth it. There's also a library called [Downloadify](https://github.com/dcneiner/Downloadify) that uses Flash to do it, but that also requires hosting a SWF file that I think would have to be added to PrairieLearn itself.

**Comment by mwest1066** [comment]
Sorry to be such a stickler with this, but would you mind rebasing these two commits onto current master, rather than just doing a merge. The merge results in an excessively complex history. One easy way to do this is to make a new branch (called, e.g., "base64") starting from current master (2d309c3e38064484a19d10ace4e129b9bbdd1bc8). Then cherry-pick the two commits over to this new branch, and issue a pull request for the base64 branch.

Regarding the Safari issue, it's no problem, I remember the problems with non-Chrome, non-FF, and I think the current solution is the best one. I definitely don't think we should use Flash shims!

**Comment by mvd7793** [comment]
No worries -- It's my job to figure out how to do the merge the same way the project does! I think I changed this PR to a rebase instead of a merge. How can you tell what commit it starts from? (I can see the branch, but I'm not sure where the last pre-PR commit is).

If I didn't get it right this time, I'll do the new pull req/cherry pick. Figured I should try to learn how to do it the "right" way before abandoning this pull req.

**Comment by mwest1066** [comment]
Perfect, thanks! Merged.

In general, my workflow on github goes like this:

- Fork the upstream repo.
- Make a dev branch myself from master.
- Work on my dev branch, issue PRs against it back to upstream.
- Never commit anything to master myself.
- Whenever I want, pull new master from upstream to stay up-to-date, including getting my own merged committees back from upstream.

**Comment by mvd7793** [comment]
Makes sense! I'll use that in the future. How can you tell what commit the
PR branches off of? Looking at the commit history of the branch?

**Comment by mwest1066** [comment]
I use this alias:

    git config --global alias.la "log --all --graph --date=short --format=format:\"%C(yellow)%h%Creset %cd%Cred%d %Cblue%cn%Creset %s\""

Then I just do "git la" to see exactly what the tree looks like and where my current branch came from.

My git notes are at: http://lagrange.mechse.illinois.edu/git_quick_ref/

**Pull request merged**
