### PR TITLE
Okta / OpenID Connect Login Method

### LINKED ISSUE #8845: Support authentication using Okta / OpenIDConnect
Me and my senior design team at Iowa State University are using this to create a learning environment for one of our courses. We would like to be able to use ISU's existing Okta SSO infrastructure to connect to PrairieLearn.

We already have a mostly functioning setup in my forked repo (https://github.com/myriath/PrairieLearn/tree/oktaintegration), just trying to get the login button to appear when running in production. I think it has something to do with the supported providers in the postgres database. I am not very experienced with SQL and am wondering how I might fix that.

Initially, I started this for Okta alone but it has expanded to a more general OIDC interface using passport-openidconnect, with each part being configurable.

### PR DESCRIPTION
**Pull request by myriath**
This pull request aims to resolve #8845 by adding a configurable OpenID Connect login method. It uses the same ideas as from other login methods for configuration and login button display. It also uses a similar login flow to the azure / saml login methods.

Adds passport-openidconnect v0.1.1 to dependencies. This is used to handle OpenID Connect's auth flow.

Added config variables for OpenID Connect. These include an enable variable, issuer, auth url, token url, user info url, client secret / id, and redirect url. Also includes configurations for the returned uid, name, and uin keys, as well as the link colors, text, and image for the login page.
The default okta login link looks like this:
image

Adds migrations for putting OID as a supported authn provider. This allows the new login link to appear when configured.

Added passport strategy 'openidconnect'. This is where the config variables are used to establish the auth flow using passport-openidconnect.

Adds login and callback pages "/pl/oidlogin" and "/pl/oidcallback". These pages are used in the auth flow for OpenID Connect.

Resolves #8845

### CODE REVIEW

**Comment by myriath** [comment]
I have reviewed and hereby sign the CLA

**Comment by nwalters512** [comment]
👋 thanks for contributing! Unfortunately, this is a difficult PR for us to accept. As we don't have access to an Okta instance or other institutional OpenID Connect provider, we won't be able to properly test and maintain this in the long run. I'd encourage you to keep this code alive in your fork, which is our recommendation for folks that need to make institution-specific changes to PrairieLearn.

**Comment by myriath** [comment]
Thanks for responding!
I completely understand, but I would like to let you know in case you didn't know; https://developer.okta.com/ allows you to set up an Okta instance completely for free with just a few clicks. If all you need to do is test it, one of these instances should be more than enough.

**Comment by nwalters512** [comment]
After talking further with the team, the consensus is that we unfortunately aren't able to commit to supporting this change at this time. As mentioned above, we encourage you to maintain these changes in your fork of PrairieLearn!

**Pull request closed without merging**
