### PR TITLE
PrairieLearn External grader local config memory size change

### PR DESCRIPTION
**Pull request by Victorsss-Orz**
This is a change to the config file that should have been changed at the same time as this: https://github.com/PrairieLearn/PrairieLearn/pull/8487 but was missed

### CODE REVIEW

**Comment by Victorsss-Orz** [comment]
I have reviewed and hereby sign the CLA

**Review by SethPoulsen — APPROVED** [review]
Looks good, thanks Victor!

**Review by trombonekenny — DISMISSED** [review]
IMO, either use bit shifting, or don't use bit shifting (I'm not a fan of the understandability of `<<` outside of people doing computer architecture) but don't combine multiplication and bit shifting.

**Review by nwalters512 — APPROVED** [review]
Bit shifting matches what was done in #8487, so I'm going to go ahead and approve this.

**Comment by SethPoulsen** [comment]
Right now this is consistent with the way its being done in the other PL configs. If we were going to change it, we would need to change it everywhere for consistency. I think its best to leave it for now. 

If we want to get rid of bitshifting everywhere, I don't mind because I'm not a huge fan of it either. But I think that's outside the scope of this PR.

**Pull request merged**
