### PR TITLE
Feat: pl-order-block ordered grading method now use partial credit and minor code cleanup

### LINKED ISSUE #6513: Allow pl-order-block to use partial credit for ordered method
In `pl-order-block`, from my understanding, the "ordered" method is similar to the ranking/dag methods where the ranking is implicitly the order of correct answers. With that in mind, would it make sense to include partial credit support for the ordered method using the same principle as ranking or dag?

There is, of course, the workaround, which is to set the method to ranking and give each answer a strictly increasing ranking number, but since these are equivalent it might be simpler to just allow the same partial credit to be used.

### PR DESCRIPTION
**Pull request by Frozemint**
Per #6513, the `ordered` grading method for `pl-order-block` currently uses an "all-or-nothing" approach for grading answers. Either the student gets 100% for correctly ordering all of the answer, or the student gets 0%.

This PR adds partial credit support to the `ordered` grading method by using the workaround mentioned in the original issue: the grading code now add a strictly increasing `ranking` number to the `true_answer_list` when the grading method is set to `ordered`, and then reuse the grading logic for `ranking` and `dag` to grade the `ordered` submission. This PR will close #6513.

Included in this PR are minor code cleanups... I found and cleaned up a few snippets of duplicate code while working on this PR.

This PR is still work in progress and needs to be tested further. Feel free to have a look and fix anything that I might have missed.

### CODE REVIEW

**Comment by Frozemint** [comment]
Since the grading method `ordered` now supports partial credit, should partial credits be enabled or disabled by default? Currently the behaviour for `ordered` is that no partial credit is given by default (because it wasn't supported). This behaviour needs to be determined in order to fixed the failing test, which are outdated and assumes `ordered` does not give partial credit.

**Comment by jonatanschroeder** [comment]
> Since the grading method `ordered` now supports partial credit, should partial credits be enabled or disabled by default? Currently the behaviour for `ordered` is that no partial credit is given by default (because it wasn't supported). This behaviour needs to be determined in order to fix the failing tests, which are outdated and assumes `ordered` does not give partial credit.

For backwards-compatibility, the behaviour before this change should remain, i.e., if no value is set it should not provide partial credit. Note that instructors using this option will likely expect this element to retain its current functionality when this is deployed.

**Comment by SethPoulsen** [comment]
Hi @Frozemint thanks a bunch for the contribution!

I'm sorry I missed responding to this PR for so long, I didn't know it existed for quite a while after it was opened. To make sure this doesn't happen in the future, feel free to assign the PR to me for Review or ping me on slack/email/whatever any time you are opening a PR related to `pl-order-blocks`.

I agree with @jonatanschroeder that unfortunately for historical reasons we are going to have to maintain the current defaults for the different grading modes--no partial credit for `ordered`, LCS edit distance partial credit for `dag` and `ranking`, and "how many you got right" partial credit for `unordered`. 

Right now the source code is not very clear about what the different possible partially credit settings and what the different default partial credit settings are for each grading mode. It would be really nice to have this be more clear both in the documentation and in the code. Maybe a good place to start would be a dictionary that stores the default and all possible partial credit modes for each grading mode? I don't know if that's the best but that's the first idea that comes to mind.

The last bummer here is that we actually changed this python file a ton since you opened this PR (see here: https://github.com/PrairieLearn/PrairieLearn/pull/8013 and here: https://github.com/PrairieLearn/PrairieLearn/pull/7774, which is going to give you some pretty bad merge conflicts. It honestly might be easier for you to just start over and copy paste the parts of your code that still work, instead of trying to merge. This is partially a result of me not knowing this PR existed at the time.

I'm sorry this one is turning in to so much more work than it started out being, I'm grateful that whenever you touch the code we are able to continue improving the quality bit by bit.

**Comment by Frozemint** [comment]
Thanks everyone for the clarifications. I'll go ahead and open a new fresh PR instead. Don't worry about the lost changes, there wasn't a lot of new code in this PR that can't be easily copied over. I'll keep you updated.

**Comment by Frozemint** [comment]
I am closing this PR in favour of #8151.

**Pull request closed without merging**
