### PR TITLE
Separate jupyterlab base image from python installation

### PR DESCRIPTION
**Pull request by joelostblom**
@nwalters512 @echuber2 This is a follow up on https://github.com/PrairieLearn/PrairieLearn/issues/10719. It should eventually be merged/synced with https://github.com/PrairieLearn/PrairieLearn/pull/9831, but I wanted to upload a draft of what I was thinking and get suggestions. The purpose is to allow people to run a more lightweight base image and have more control over both the system packages, programming languages and language-specific packages that are installed.

### CODE REVIEW

**Comment by joelostblom** [comment]
I have reviewed and hereby sign the CLA

**Comment by nwalters512** [comment]
You'll need to update our CI processes to build and publish the base image as needed:

- https://github.com/PrairieLearn/PrairieLearn/blob/master/.github/workflows/images.yml
- https://github.com/PrairieLearn/PrairieLearn/blob/master/.github/workflows/main.yml

You should be able to pattern-match off what's there. If you have questions, please ask.

**Comment by nwalters512** [comment]
@joelostblom do you intend to continue working on this PR? If not, let's close it to keep our list of open PRs tidy.

**Comment by nwalters512** [comment]
Since we haven't seen any movement on this PR, I'm going to close it out. If you'd like to continue work on this, I'd be more than happy to reopen it!

**Comment by joelostblom** [comment]
Sounds good, I mean to come back to this at some point, but there is just too much at work right now.

**Comment by nwalters512** [comment]
For posterity, this work was restarted in #11096.

**Pull request closed without merging**
