### PR TITLE
docs: Allow indented code blocks

### PR DESCRIPTION
**Pull request by mwest1066**
Mkdocs does not allow indented code blocks by default in markdown (unlike GitHub markdown, which does allow this). See below for an example of bad rendering in our current docs due to this. This PR adds the [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) extension to fix this, as recommended [here](https://github.com/squidfunk/mkdocs-material/issues/2639). I checked the rendering locally and it looks fine (see below), although it does add an extra box around each code block. An alternative approach would be to dedent all the code blocks, as we do on other pages such as https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/installingLocal.md?plain=1#L7-L11
What does everyone think about dedenting versus using this extension?

# Example of problem in the current docs

For example, in the native install docs we have indented blocks like this: https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/installingNative.md?plain=1#L18-L35
which renders into this mess:
image

# Fixed example with the new extension

The above example now renders like this:
image

### CODE REVIEW

**Review by eliotwrobson — APPROVED** [review]
If tested locally I don't see any issues. This dependency is really well maintained (the maintainer has actually helped out with previous PRs here!)

**Comment by mwest1066** [comment]
> If tested locally I don't see any issues. This dependency is really well maintained (the maintainer has actually helped out with previous PRs here!)

Oh nice! Maintenance was the main thing I was worried about so this is very good to know.

**Review by jonatanschroeder — APPROVED** [review]
This might be an opportunity to fix some other places that have this issue. Here's what I found, feel free to push them into a future issue.

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/assessment.md?plain=1#L375-L387

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/dev-guide.md?plain=1#L19-L24 (not sure this should be an item, though)

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/dev-guide.md?plain=1#L68-L88
https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/dev-guide.md?plain=1#L100-L104
https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/dev-guide.md?plain=1#L108-L121
(plus a few others in dev-guide)

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/docker.md?plain=1#L38-L72

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/getStarted.md?plain=1#L26-L41
(plus a few more in getStarted.md)

https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/installing.md?plain=1#L15-L19

Also a few in installingLocal.md, running-in-production/admin-user.md, running-in-production/docker-compose.md, and workshop/lesson2.md.

**Review by nwalters512 — APPROVED** [review]
LGTM! The following patch removes the extra box around code blocks:

```diff
diff --git a/docs/extra.css b/docs/extra.css
new file mode 100644
index 000000000..3de82dd14
--- /dev/null
+++ b/docs/extra.css
@@ -0,0 +1,7 @@
+.rst-content div[class^=highlight] {
+  border: none;
+}
+
+.rst-content div[class^=highlight] pre {
+  padding: 0;
+}
diff --git a/mkdocs.yml b/mkdocs.yml
index eaee9eb1d..71eaf006d 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -19,6 +19,9 @@ extra_javascript:
   - mathjax-config.js
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
 
+extra_css:
+  - extra.css
+
 nav:
 - Main: 'index.md'
 - Getting Started:
```

**Comment by mwest1066** [comment]
> The following patch removes the extra box around code blocks:

Thanks! Applied in https://github.com/PrairieLearn/PrairieLearn/pull/8194/commits/11a7e757622c4942f50295dcd1ee62fc3ccf29e5

**Comment by mwest1066** [comment]
> This might be an opportunity to fix some other places that have this issue. Here's what I found, feel free to push them into a future issue.

Thanks! Pulled out into https://github.com/PrairieLearn/PrairieLearn/issues/8199

**Pull request merged**
