### PR TITLE
docs: update images for viewing question reports

### LINKED ISSUE #5404: Update screenshot of issues page in docs
The docs related to issue reporting (https://prairielearn.readthedocs.io/en/latest/assessment/#issue-reporting) have a really outdated screenshot of the issues page. This should probably be updated to the new view of the page.

Related: #4093

### PR DESCRIPTION
**Pull request by michaelfromyeg**
As title; I stuck with the pink borders (as done in more recent reference images) for consistency!

Closes #5404.

### CODE REVIEW

**Comment by michaelfromyeg** [comment]
I have reviewed and hereby sign the CLA

**Comment by michaelfromyeg** [comment]
recheck

**Review by jonatanschroeder — COMMENTED** [review]
I'm wondering if it's better to use the link from the top menu, beside the instance name? That one is visible in all contexts and may be easier to find for new instructors.

**Comment by michaelfromyeg** [comment]
That's a good point; or at least, it's definitely worth showing both. I've made the screenshot a bit taller to include the top menu as well!

**Review by jonatanschroeder — APPROVED** [review]

**Comment by nwalters512** [comment]
AFAICT, `docs/assessment-report3.png` isn't used in the docs anywhere. Should we just delete that image?

**Comment by michaelfromyeg** [comment]
Good catch; removed and renamed 4->3!

**Review by nwalters512 — APPROVED** [review]

**Pull request merged**
