### PR TITLE
[r] 'Unminimize' documentation so that students can do 'man grep' etc

### PR DESCRIPTION
**Pull request by eddelbuettel**
Runs script /usr/local/sbin/unminimize which also wants a current system so with additional 'apt upgrade', also installs package 'man-db' for man command

As discussed slack, this seems to move the needle from about 2.2gb to 2.5gb.

### CODE REVIEW

**Review by nwalters512 — APPROVED** [review]
300MB is an unfortunate increase. Oh well!

**Comment by eddelbuettel** [comment]
I have a small improvement due to @echuber2 pending, currently running a build to see if it makes a size difference.

**Comment by eddelbuettel** [comment]
@nwalters512 Take a look now.

**Review by nwalters512 — APPROVED** [review]
New changes look good. Let me know when you're happy with everything and I'll merge 🚀

**Comment by eddelbuettel** [comment]
@nwalters512 I cannot think of an immediate improvement on either process or size.  I think merging now is good though.  If/when @echuber2 or I come up with an improvement scheme we can do a follow-up PR.

**Comment by eddelbuettel** [comment]
So sorry.  One more coming.  (See slack.) We stop now.

No size impact.  Epsilon improvement to the Dockerfile.

**Pull request merged**
