### PR TITLE
Update Python dependencies

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Not updated:

* `pygraphviz`, `rpy2`, `tzlocal` (as usual, see #8610);
* `lxml` (major version bump, probably good to test separately in #9141 and #9150);
* `jupyter-collaboration` (major version bump, should test separately in #9130).

Faker also had a major bump, but breaking changes do not seem to be consequential.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
@eliotwrobson can you check what this means?

```
 /home/runner/work/PrairieLearn/PrairieLearn/apps/prairielearn/elements/pl-dataframe/pl-dataframe.py:49:63 - error: "is_period_dtype" is not a known member of module "pandas.api.types" (reportGeneralTypeIssues)
```

**Comment by eliotwrobson** [comment]
@jonatanschroeder I think the `is_period_dtype` function had its import changed, see the example in the documentation:

https://pandas.pydata.org/docs/reference/api/pandas.api.types.is_period_dtype.html

Should be as simple as changing the module on the function call to match the above example.

**Comment by jonatanschroeder** [comment]
https://github.com/pandas-dev/pandas/blob/a671b5a8bf5dd13fb19f0e88edc679bc9e15c673/pandas/core/dtypes/common.py#L408-L413

**Review by eliotwrobson — APPROVED** [review]
Changes all look reasonable! This is updating a few different dependency files at once but I don't really anticipate any of the changes to be breaking.

**Pull request merged**
