### PR TITLE
Add pandoc to graders/r/Dockerfile

### PR DESCRIPTION
**Pull request by eddelbuettel**
This minimal PR adds `pandoc` ~and `pandoc-citeproc`~ to the R autograder container.

### CODE REVIEW

**Comment by nwalters512** [comment]
Thanks for the PR! Can you compare the size of the Docker image before and after this change? We need to be cognizant of how heavy these "base" images are.

**Comment by eddelbuettel** [comment]
Completely agree on size being a factor.  If anything, the (pre-PR) image leans heavier on the R package content than we "must" but has a few nice data packages. I would trim there.  `pandoc` has become a base layer we really need, it was my omission that it dropped.  (Our `Dockerfile` in the pre-decessor repo had it.)

```sh
edd@rob:~$ docker images | grep grader-r
prarielearn/grader-r                 withPR6309      fbc7a958fdd0   26 seconds ago   1.39GB
prairielearn/grader-r                latest          f598864eabf0   2 weeks ago      1.12GB
edd@rob:~$ 
```

The container builds in under a minute (as all the CRAN packages comes as binaries, we'll soon have a mirror for that binary repo to announce too).

**Comment by nwalters512** [comment]
Gotcha! According to https://github.com/jgm/pandoc-citeproc, `pandoc-citeproc` is no longer maintained, as `pandoc` comes with `citeproc` built-in. Is it possible to remove that package?

**Comment by eddelbuettel** [comment]
Great catch.  It's kinda reflexive for me as they used install as pairs on Debian / Ubuntu systems.  

Commit adjusted and force-pushed.  Now adds only `pandoc`.

**Review by nwalters512 — APPROVED** [review]

**Pull request merged**
