### PR TITLE
Added api call for course_instance_access_rules

### PR DESCRIPTION
**Pull request by mepstein-gh**
Added an api call for a course instance's course_instance_access_rules.

I pretty much followed what was done in this PR:

 #2389

where I added an api call for an assessment's assessment_access_rules.

I also corrected what I believe were a couple of minor errors in:

api/v1/endpoints/queries.sql

and:

api/v1/endpoints/courseInstanceGradebook/index.js

### CODE REVIEW

**Comment by mepstein-gh** [comment]
Is it necessary to run tests as specified here:

`[](https://prairielearn.readthedocs.io/en/latest/installingLocal/#tests-from-shell)`

For instance, I tried running:

`./docker/test_js.sh`

and it ran for a while, with almost all tests passing, I think just a handful failed, and then it aborted with some more failures.  But I have a feeling that these were things that weren't necessarily expected to pass in my local setup.  It did pass the tests run automatically for this PR, as shown above.

**Comment by mepstein-gh** [comment]
Sample output for new API URL:

[http://localhost:3000/pl/api/v1/course_instances/2/course_instance_access_rules](http://localhost:3000/pl/api/v1/course_instances/2/course_instance_access_rules)

[
  {
    "role": null,
    "uids": null,
    "end_date": "2400-05-13T23:59:59-05",
    "start_date": "1800-01-19T00:00:01-05:50",
    "institution": "Any",
    "course_instance_access_rule_id": 2,
    "course_instance_access_rule_number": 1
  }
]

Hmmm -- I just realized there isn't really anything in this about the course instance.  Let me go and modify that query slightly (plus I'm sure someone will suggest it :-) ).

**Comment by mepstein-gh** [comment]
Output is now:

```
[
  {
    "role": null,
    "uids": null,
    "end_date": "2400-05-13T23:59:59-05",
    "start_date": "1800-01-19T00:00:01-05:50",
    "institution": "Any",
    "course_instance_id": 2,
    "course_instance_course_id": 2,
    "course_instance_long_name": "Spring 2015",
    "course_instance_short_name": "Sp15",
    "course_instance_access_rule_id": 2,
    "course_instance_access_rule_number": 1
  }
]
```

**Comment by mepstein-gh** [comment]
I have reviewed and hereby sign the CLA

**Comment by mepstein-gh** [comment]
@mwest1066: I saw your comment/request to make two separate PRs, so I was going to pull some changes out of here (both are in here currently).  I was just in the process of doing that, should be done shortly.

**Comment by mwest1066** [comment]
> @mwest1066: I saw your comment/request to make two separate PRs, so I was going to pull some changes out of here (both are in here currently). I was just in the process of doing that, should be done shortly.

Excellent, thanks! I merged with master to pick up the fix for the CI error. That should be resolved now.

**Comment by mepstein-gh** [comment]
OK, this is ready for any additional comments from reviewers.  Thanks.

**Comment by mwest1066** [comment]
@jonatanschroeder can you handle this PR? It needs updating for the `prairielib` changes at least, which it might be easiest to just do yourself.

**Review by jonatanschroeder — APPROVED** [review]
Other than the changes Matt mentioned (which I've handled myself) this looks good.

**Pull request merged**
