### PR TITLE
suppress opt-in dialog for announcements

### PR DESCRIPTION
**Pull request by kurmasz**
Suppress the opt-in dialog for Jupyter announcements that appears every time the workspace opens.

https://github.com/PrairieLearn/PrairieLearn/assets/397476/71da0926-9408-4d9f-90a9-170c70ec7681

### CODE REVIEW

**Comment by kurmasz** [comment]
I have reviewed and hereby sign the CLA

**Comment by kurmasz** [comment]
I have reviewed and hereby sign the CLA.

**Review by nwalters512 — APPROVED** [review]
Looks reasonable, thanks for this! My only question is whether it might be better to put this in `install.sh`.

**Comment by kurmasz** [comment]
I don't know Docker well enough to have an opinion.  I'm fine with whatever you decide.

**Comment by nwalters512** [comment]
Would you mind moving it into `install.sh`? This has nothing to do with Docker in general, I just think that might be more consistent with how this and other workspaces are structured.

**Comment by kurmasz** [comment]
Ok, I moved it over and made sure the new image works in production.

**Review by jonatanschroeder — APPROVED** [review]
Tested locally, works for me.

**Pull request merged**
