### PR TITLE
feat: Symbolic unicode translate

### PR DESCRIPTION
**Pull request by eliotwrobson**
Added a unicode translation step to the sympy expression parser, along with corresponding unit tests in the test suite. Be sure to test locally, since I haven't been able to get PL running locally. May be worth adding additional examples to the test suite, as I only used one.

### CODE REVIEW

**Review by jonatanschroeder — APPROVED** [review]
Seems to work locally. This also has the advantage that the code now accepts μ0 and mu0 as equivalent.

You converted variables, do you want to also convert function names, for completeness?

**Comment by eliotwrobson** [comment]
> You converted variables, do you want to also convert function names, for completeness?

Good catch, I'll do that really fast.

**Comment by eliotwrobson** [comment]
Just added automated conversion for custom function names, should work the same as for the variables.

**Comment by jonatanschroeder** [comment]
> Just added automated conversion for custom function names, should work the same as for the variables.

Looks good. Approval stands.

**Pull request merged**
