### PR TITLE
Add FAQ entry describing local templates

### PR DESCRIPTION
**Pull request by mwest1066**
This is a temporary workaround until #4701 is implemented.

### CODE REVIEW

**Comment by echuber2** [comment]
@mwest1066 It may be confusing that the example doesn't create a clickable link to either of the named files (they are just text labels). Would it better to expand the example to include clickable links to stuff in `clientFilesQuestion`, or to simplify the example (for example, just parameterize some integers in a math problem)?

**Comment by mwest1066** [comment]
> @mwest1066 It may be confusing that the example doesn't create a clickable link to either of the named files (they are just text labels). Would it better to expand the example to include clickable links to stuff in `clientFilesQuestion`, or to simplify the example (for example, just parameterize some integers in a math problem)?

Done.

**Comment by echuber2** [comment]
OK, looks good

**Comment by echuber2** [comment]
Maybe we should add a note about where two vs. three `{` are needed? This seems like a footgun if the instructor is new to Mustache.

**Comment by mwest1066** [comment]
> Maybe we should add a note about where two vs. three `{` are needed? This seems like a footgun if the instructor is new to Mustache.

Done.

**Pull request merged**
