### PR TITLE
Replace ts-node with tsx

### PR DESCRIPTION
**Pull request by nwalters512**
This PR replaces `ts-node` with `tsx`. The former has had some compatibility issues with recent versions of `@swc/core` and isn't quite as smooth when it comes to ESM support. The latter is supported, uses esbuild by default so it's very fast, and has pretty seamless support for ESM/CJS interop. We're still not yet using ESM in this codebase, but we will in the near future.

### CODE REVIEW

**Comment by nwalters512** [comment]
It looks like there is an issue where `tsx` doesn't play nicely with our usage of `requirejs` for v2 questions. We'll want to land #7482 first, which I think is safe to do now. I confirmed that the server boots fine if we remove all imports of `lib/require-frontend`.

**Comment by nwalters512** [comment]
I believe this is now blocked on the move to Node 20.

**Comment by nwalters512** [comment]
Once we get to Node 20, this will also be blocked by https://github.com/privatenumber/tsx/issues/389.

**Review by jonatanschroeder — COMMENTED** [review]
I tested locally and it seems to be working in the same way as with ts-node before. I'm not sure if I should be seeing any difference or what to look for, but if you tell me what I should be testing for I'm happy to expand.

**Review by mwest1066 — APPROVED** [review]
Works for me!

**Comment by nwalters512** [comment]
> I tested locally and it seems to be working in the same way as with ts-node before. I'm not sure if I should be seeing any difference or what to look for, but if you tell me what I should be testing for I'm happy to expand.

If you're not seeing any difference, things are working as expected! I wouldn't expect there to be any observable difference until we start running native ESM.

**Pull request merged**
